-- ============================================================================
-- VALMONT DATA — demo seed (customers, saved numbers, orders, bundle usage,
-- auto-reload opt-ins, float, webhooks)
-- Generated by : node scripts/seed-demo.js --sql   (edit lib/demo-data.js and re-run,
--                never hand-edit this file)
-- Anchored to  : 2026-08-11T18:40:53.330Z
-- Environment  : DEMO / STAGING Supabase ONLY — do not run against production.
-- Safe to re-run: skips itself when public.orders already has rows.
-- Demo logins  : PIN 1234 → 0241234567 (Ama Serwaa), 0209876543 (Kofi Mensah), 0551112233 (Abena Owusu), 0502345678 (Yaw Boateng), 0273344556 (Esi Asante)
-- ============================================================================

do $$
begin
  if exists (select 1 from public.orders) then
    raise notice 'Valmont Data demo seed SKIPPED — orders table is not empty.';
    return;
  end if;

  -- demo customer accounts (scrypt pin_hash; PINs listed in the header)
  insert into public.customers (phone, email, name, pin_hash, created_at) values
    ('0241234567', 'ama.serwaa@example.com', 'Ama Serwaa', '43d593ef1d3d7f9d4386cd27b199fa71:3aed832fa6058065c5f3d4ae909e184048013e5c3d16dab88b1c43a16ecd31a0996288f6feaab149980f444a7b304766cbab8972f14121cbe28b324144834472', '2026-06-26T19:25:53.330Z'),
    ('0209876543', 'kofi.mensah@example.com', 'Kofi Mensah', 'fcf49feb43bdddf9a7c3c278adbd0877:7a4d2b30156a7c31622bcddc76d1972ed7738051b1647a5495f5e28ca6ec1f37e2ad1338f835b0bc77c3d56ba79fc5f0f5951c60b26254a67e1f284e7551eec4', '2026-06-30T19:01:53.330Z'),
    ('0551112233', 'abena.owusu@example.com', 'Abena Owusu', '60cb2886eb29a982267c6d1aa05788f4:e99c811843f9af5261c46e3c6e65b4b08b553bb34564f8c8365b40a2be8a23d6ffe750aae10f883daba34c773c08eb2026c327cd9c986e59fcb624b175d88936', '2026-07-04T20:11:53.330Z'),
    ('0502345678', 'yaw.boateng@example.com', 'Yaw Boateng', '8838d820a4c5f7993beeff8f548ab889:d4634b9757c78d8216b0013118fd28f04164d8b167103ff5ab6a6e10a09393219bde5fad721e79b79105a87738fd8a95a600ac5ab25b93f8eff6344ba95344d4', '2026-07-08T19:01:53.330Z'),
    ('0273344556', 'esi.asante@example.com', 'Esi Asante', 'f02d610699fe423731dff7310b5c79db:cb52d542195386e8d690766c0709785775f99f30d918ba23351494410793659c4df6de4d9852a5ad520d9a0ac3a541175de74a468c541b503674263e50daf9f0', '2026-07-12T19:03:53.330Z')
  on conflict (phone) do nothing;

  -- saved data lines + MoMo numbers
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0241234567', 'My line', '2026-07-02T20:07:53.330Z' from public.customers where phone = '0241234567'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0559988776', 'Mum''s line', '2026-07-03T20:07:53.330Z' from public.customers where phone = '0241234567'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0245678901', 'My MoMo', '2026-07-04T20:36:53.330Z' from public.customers where phone = '0241234567'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0209876543', 'My line', '2026-07-05T20:52:53.330Z' from public.customers where phone = '0209876543'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0201122334', 'Shop line', '2026-07-06T21:34:53.330Z' from public.customers where phone = '0209876543'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0505566778', 'MoMo', '2026-07-07T18:43:53.330Z' from public.customers where phone = '0209876543'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0551112233', 'My line', '2026-07-08T21:33:53.330Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0247788990', 'Work line', '2026-07-09T21:11:53.330Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0559998877', 'MoMo', '2026-07-10T18:47:53.330Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0241212121', 'Dad''s MoMo', '2026-07-11T18:52:53.330Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0502345678', 'My line', '2026-07-12T18:44:53.330Z' from public.customers where phone = '0502345678'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0276655443', 'Family line', '2026-07-13T21:11:53.330Z' from public.customers where phone = '0502345678'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0501234321', 'Business MoMo', '2026-07-14T19:23:53.330Z' from public.customers where phone = '0502345678'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0273344556', 'My line', '2026-07-15T19:20:53.330Z' from public.customers where phone = '0273344556'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0561122334', 'Brother''s line', '2026-07-16T20:44:53.330Z' from public.customers where phone = '0273344556'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0277788990', 'MoMo', '2026-07-17T21:24:53.330Z' from public.customers where phone = '0273344556'
  on conflict (customer_id, kind, phone) do nothing;

  -- orders (bundle/network/customer ids resolved from the base seed)
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260806-6799', '0250812692',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         17.00, 11.90, 'delivered',
         'VP-260806-MDFU', 'REM-80322636',
         '{"driver":"remadata","order_id":"REM-80322636","status":"success","network":"mtn","size_mb":3072,"phone":"0250812692"}'::jsonb,
         1,
         NULL,
         '2026-08-06T11:06:44.986Z', '2026-08-06T11:09:04.942Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260729-7594', '0209876543',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 30720),
         (select id from public.networks where code = 'telecel'),
         110.00, 98.70, 'delivered',
         'VP-260729-32J9', 'REM-99359595',
         '{"driver":"remadata","order_id":"REM-99359595","status":"success","network":"telecel","size_mb":30720,"phone":"0209876543"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-07-29T08:01:51.445Z', '2026-07-29T08:03:32.018Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-5150', '0271137953',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 30720),
         (select id from public.networks where code = 'airteltigo'),
         117.00, 106.00, 'failed',
         'VP-260808-AH6A', NULL,
         '{"ok":false,"error":"Supplier API error: SUBSCRIBER_NOT_FOUND","raw":{"driver":"mock","order":"VD-260808-5150"}}'::jsonb,
         1,
         NULL,
         '2026-08-08T19:59:46.885Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-4884', '0597066765',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         6.00, 3.90, 'delivered',
         'VP-260719-YWN8', 'REM-15431188',
         '{"driver":"remadata","order_id":"REM-15431188","status":"success","network":"mtn","size_mb":1024,"phone":"0597066765"}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-19T19:07:32.395Z', '2026-07-19T19:10:35.674Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260721-9488', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         (select id from public.networks where code = 'telecel'),
         39.50, 35.50, 'delivered',
         'VP-260721-YCXQ', 'REM-94503305',
         '{"driver":"remadata","order_id":"REM-94503305","status":"success","network":"telecel","size_mb":10240,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-07-21T09:13:51.787Z', '2026-07-21T09:18:46.987Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260720-3007', '0266168899',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 8192),
         (select id from public.networks where code = 'mtn'),
         43.00, 32.60, 'delivered',
         'VP-260720-2H3S', 'REM-10770728',
         '{"driver":"remadata","order_id":"REM-10770728","status":"success","network":"mtn","size_mb":8192,"phone":"0266168899"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-07-20T22:22:57.886Z', '2026-07-20T22:26:05.753Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-8219', '0595499137',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 51200),
         (select id from public.networks where code = 'mtn'),
         220.00, 185.00, 'delivered',
         'VP-260807-TBQH', 'REM-51912483',
         '{"driver":"remadata","order_id":"REM-51912483","status":"success","network":"mtn","size_mb":51200,"phone":"0595499137"}'::jsonb,
         1,
         NULL,
         '2026-08-07T01:23:35.734Z', '2026-08-07T01:24:40.159Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260721-1596', '0501580260',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260721-GJYS', 'REM-16353422',
         '{"driver":"remadata","order_id":"REM-16353422","status":"success","network":"telecel","size_mb":102400,"phone":"0501580260"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-21T19:40:32.071Z', '2026-07-21T19:45:30.699Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260801-8223', '0595948207',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         12.00, 8.10, 'delivered',
         'VP-260801-WK5G', 'REM-12541517',
         '{"driver":"remadata","order_id":"REM-12541517","status":"success","network":"mtn","size_mb":2048,"phone":"0595948207"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-08-01T13:55:58.626Z', '2026-08-01T13:58:19.948Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260715-5421', '0590640104',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 20480),
         (select id from public.networks where code = 'mtn'),
         93.00, 73.00, 'delivered',
         'VP-260715-RM7J', 'REM-51423657',
         '{"driver":"remadata","order_id":"REM-51423657","status":"success","network":"mtn","size_mb":20480,"phone":"0590640104"}'::jsonb,
         1,
         NULL,
         '2026-07-15T01:55:24.653Z', '2026-07-15T01:58:39.891Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260809-6077', '0279039208',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 30720),
         (select id from public.networks where code = 'airteltigo'),
         117.00, 106.00, 'delivered',
         'VP-260809-MVK5', 'REM-63109304',
         '{"driver":"remadata","order_id":"REM-63109304","status":"success","network":"airteltigo","size_mb":30720,"phone":"0279039208"}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-08-09T13:02:50.884Z', '2026-08-09T13:05:24.680Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-2611', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 8192),
         (select id from public.networks where code = 'mtn'),
         43.00, 32.60, 'delivered',
         'VP-260808-UQS2', 'REM-10406868',
         '{"driver":"remadata","order_id":"REM-10406868","status":"success","network":"mtn","size_mb":8192,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-08T06:46:27.769Z', '2026-08-08T06:50:42.760Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-5667', '0550640824',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         28.00, 18.90, 'delivered',
         'VP-260807-H7LM', 'REM-73268060',
         '{"driver":"remadata","order_id":"REM-73268060","status":"success","network":"mtn","size_mb":5120,"phone":"0550640824"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-07T19:48:18.722Z', '2026-08-07T19:52:12.957Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-9029', '0547000432',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 51200),
         (select id from public.networks where code = 'mtn'),
         220.00, 185.00, 'delivered',
         'VP-260719-SYQ7', 'REM-17377712',
         '{"driver":"remadata","order_id":"REM-17377712","status":"success","network":"mtn","size_mb":51200,"phone":"0547000432"}'::jsonb,
         1,
         NULL,
         '2026-07-19T04:28:08.636Z', '2026-07-19T04:32:17.435Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260802-8629', '0269887748',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         12.00, 8.10, 'delivered',
         'VP-260802-V3VV', 'REM-16246847',
         '{"driver":"remadata","order_id":"REM-16246847","status":"success","network":"mtn","size_mb":2048,"phone":"0269887748"}'::jsonb,
         1,
         NULL,
         '2026-08-02T16:37:23.412Z', '2026-08-02T16:41:15.752Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260802-2030', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 4096),
         (select id from public.networks where code = 'mtn'),
         23.00, 16.60, 'delivered',
         'VP-260802-4VR3', 'REM-48044253',
         '{"driver":"remadata","order_id":"REM-48044253","status":"success","network":"mtn","size_mb":4096,"phone":"0559988776"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-08-02T09:17:58.222Z', '2026-08-02T09:19:29.942Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260809-2083', '0551112233',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 6144),
         (select id from public.networks where code = 'mtn'),
         35.00, 24.50, 'delivered',
         'VP-260809-J63L', 'REM-31286903',
         '{"driver":"remadata","order_id":"REM-31286903","status":"success","network":"mtn","size_mb":6144,"phone":"0551112233"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-09T00:25:47.300Z', '2026-08-09T00:29:00.289Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260727-2835', '0596109346',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         6.00, 3.90, 'delivered',
         'VP-260727-8KUQ', 'REM-62798147',
         '{"driver":"remadata","order_id":"REM-62798147","status":"success","network":"mtn","size_mb":1024,"phone":"0596109346"}'::jsonb,
         1,
         NULL,
         '2026-07-27T07:08:37.791Z', '2026-07-27T07:10:12.782Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260731-2157', '0561122334',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 10240),
         (select id from public.networks where code = 'airteltigo'),
         39.00, 35.50, 'delivered',
         'VP-260731-CLVP', 'REM-26827162',
         '{"driver":"remadata","order_id":"REM-26827162","status":"success","network":"airteltigo","size_mb":10240,"phone":"0561122334"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-31T11:59:19.479Z', '2026-07-31T12:02:44.838Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-6770', '0266199330',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         28.00, 18.90, 'pending',
         NULL, NULL,
         NULL,
         0,
         (select id from public.customers where phone = '0273344556'),
         '2026-08-07T17:25:24.938Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260804-2384', '0257013265',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 10240),
         (select id from public.networks where code = 'mtn'),
         52.00, 38.50, 'delivering',
         'VP-260804-CT8W', NULL,
         NULL,
         1,
         NULL,
         '2026-08-04T20:17:34.757Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260809-4475', '0551112233',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'refunded',
         'VP-260809-N9VC', NULL,
         '{"refunded":true,"reason":"Amount mismatch: webhook 415.00 vs order 405.00"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-09T07:21:28.390Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260715-8214', '0272292320',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 10240),
         (select id from public.networks where code = 'airteltigo'),
         39.00, 35.50, 'delivered',
         'VP-260715-DENA', 'REM-92924717',
         '{"driver":"remadata","order_id":"REM-92924717","status":"success","network":"airteltigo","size_mb":10240,"phone":"0272292320"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-15T07:32:36.341Z', '2026-07-15T07:34:44.525Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-5760', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         (select id from public.networks where code = 'telecel'),
         39.50, 35.50, 'delivered',
         'VP-260719-AY27', 'REM-43632377',
         '{"driver":"remadata","order_id":"REM-43632377","status":"success","network":"telecel","size_mb":10240,"phone":"0559988776"}'::jsonb,
         2,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-19T21:08:40.652Z', '2026-07-19T21:12:18.679Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260716-3458', '0275346242',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 30720),
         (select id from public.networks where code = 'airteltigo'),
         117.00, 106.00, 'delivered',
         'VP-260716-Q73K', 'REM-87025588',
         '{"driver":"remadata","order_id":"REM-87025588","status":"success","network":"airteltigo","size_mb":30720,"phone":"0275346242"}'::jsonb,
         1,
         NULL,
         '2026-07-16T02:23:56.274Z', '2026-07-16T02:27:10.328Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260804-5883', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         28.00, 18.90, 'delivered',
         'VP-260804-QXY3', 'REM-93275626',
         '{"driver":"remadata","order_id":"REM-93275626","status":"success","network":"mtn","size_mb":5120,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-04T12:37:01.105Z', '2026-08-04T12:41:18.357Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260728-3783', '0569485282',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 5120),
         (select id from public.networks where code = 'airteltigo'),
         19.90, 18.00, 'delivering',
         'VP-260728-TTFX', NULL,
         NULL,
         1,
         NULL,
         '2026-07-28T17:55:36.918Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260727-3210', '0502345678',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         28.00, 18.90, 'pending',
         NULL, NULL,
         NULL,
         0,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-27T16:00:10.165Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260726-9728', '0276655443',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         6.00, 3.90, 'delivered',
         'VP-260726-S3Y9', 'REM-93529305',
         '{"driver":"remadata","order_id":"REM-93529305","status":"success","network":"mtn","size_mb":1024,"phone":"0276655443"}'::jsonb,
         2,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-26T23:30:06.299Z', '2026-07-26T23:31:55.228Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260717-8085', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260717-6G94', 'REM-37729123',
         '{"driver":"remadata","order_id":"REM-37729123","status":"success","network":"telecel","size_mb":102400,"phone":"0559988776"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-17T06:21:01.949Z', '2026-07-17T06:24:22.346Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260731-6398', '0263217842',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 10240),
         (select id from public.networks where code = 'mtn'),
         52.00, 38.50, 'delivered',
         'VP-260731-HU34', 'REM-99106254',
         '{"driver":"remadata","order_id":"REM-99106254","status":"success","network":"mtn","size_mb":10240,"phone":"0263217842"}'::jsonb,
         1,
         NULL,
         '2026-07-31T00:39:51.117Z', '2026-07-31T00:44:16.054Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-3982', '0542245723',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         12.00, 8.10, 'delivered',
         'VP-260807-JH2W', 'REM-94735765',
         '{"driver":"remadata","order_id":"REM-94735765","status":"success","network":"mtn","size_mb":2048,"phone":"0542245723"}'::jsonb,
         2,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-07T16:16:50.828Z', '2026-08-07T16:18:11.964Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260715-7057', '0540982919',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         17.00, 11.90, 'failed',
         'VP-260715-F3VS', NULL,
         '{"ok":false,"error":"Invalid recipient — number cannot receive this bundle","raw":{"driver":"mock","order":"VD-260715-7057"}}'::jsonb,
         1,
         NULL,
         '2026-07-15T14:54:46.347Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260728-6616', '0502345678',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 40960),
         (select id from public.networks where code = 'mtn'),
         180.00, 159.00, 'delivered',
         'VP-260728-PY9V', 'REM-73067886',
         '{"driver":"remadata","order_id":"REM-73067886","status":"success","network":"mtn","size_mb":40960,"phone":"0502345678"}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-28T09:38:05.156Z', '2026-07-28T09:41:03.340Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-6082', '0561122334',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         17.00, 11.90, 'delivered',
         'VP-260719-SEFJ', 'REM-39715366',
         '{"driver":"remadata","order_id":"REM-39715366","status":"success","network":"mtn","size_mb":3072,"phone":"0561122334"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-19T04:47:38.622Z', '2026-07-19T04:49:25.604Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260803-9502', '0548612388',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         6.00, 3.90, 'delivered',
         'VP-260803-R8FU', 'REM-88756896',
         '{"driver":"remadata","order_id":"REM-88756896","status":"success","network":"mtn","size_mb":1024,"phone":"0548612388"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-08-03T11:02:26.613Z', '2026-08-03T11:04:13.986Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260802-8856', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 4096),
         (select id from public.networks where code = 'mtn'),
         23.00, 16.60, 'delivered',
         'VP-260802-B6RB', 'REM-54616799',
         '{"driver":"remadata","order_id":"REM-54616799","status":"success","network":"mtn","size_mb":4096,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-02T00:16:20.344Z', '2026-08-02T00:20:10.668Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260731-1914', '0201122334',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         12.00, 8.10, 'delivered',
         'VP-260731-XC9N', 'REM-23655494',
         '{"driver":"remadata","order_id":"REM-23655494","status":"success","network":"mtn","size_mb":2048,"phone":"0201122334"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-07-31T23:57:56.829Z', '2026-08-01T00:01:43.362Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260727-1989', '0265373760',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 6144),
         (select id from public.networks where code = 'mtn'),
         35.00, 24.50, 'delivered',
         'VP-260727-L7JC', 'REM-30801831',
         '{"driver":"remadata","order_id":"REM-30801831","status":"success","network":"mtn","size_mb":6144,"phone":"0265373760"}'::jsonb,
         2,
         NULL,
         '2026-07-27T21:07:21.823Z', '2026-07-27T21:09:35.781Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260717-9129', '0273344556',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 6144),
         (select id from public.networks where code = 'mtn'),
         35.00, 24.50, 'delivered',
         'VP-260717-LKLL', 'REM-21689291',
         '{"driver":"remadata","order_id":"REM-21689291","status":"success","network":"mtn","size_mb":6144,"phone":"0273344556"}'::jsonb,
         2,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-17T14:53:00.127Z', '2026-07-17T14:56:40.713Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-2399', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         6.00, 3.90, 'delivered',
         'VP-260808-FBE4', 'REM-22880886',
         '{"driver":"remadata","order_id":"REM-22880886","status":"success","network":"mtn","size_mb":1024,"phone":"0559988776"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-08-08T15:06:49.168Z', '2026-08-08T15:09:29.525Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260718-6521', '0257679524',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 20480),
         (select id from public.networks where code = 'mtn'),
         93.00, 73.00, 'delivered',
         'VP-260718-8CDL', 'REM-35137871',
         '{"driver":"remadata","order_id":"REM-35137871","status":"success","network":"mtn","size_mb":20480,"phone":"0257679524"}'::jsonb,
         2,
         NULL,
         '2026-07-18T08:32:28.113Z', '2026-07-18T08:36:14.842Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-5186', '0241234567',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         (select id from public.networks where code = 'telecel'),
         39.50, 35.50, 'delivered',
         'VP-260719-4G2T', 'REM-47348147',
         '{"driver":"remadata","order_id":"REM-47348147","status":"success","network":"telecel","size_mb":10240,"phone":"0241234567"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-19T19:46:28.677Z', '2026-07-19T19:48:47.325Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260806-1699', '0558491498',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 10240),
         (select id from public.networks where code = 'mtn'),
         52.00, 38.50, 'delivered',
         'VP-260806-9M5L', 'REM-47574191',
         '{"driver":"remadata","order_id":"REM-47574191","status":"success","network":"mtn","size_mb":10240,"phone":"0558491498"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-06T11:26:50.105Z', '2026-08-06T11:30:20.226Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260724-6374', '0242248702',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 25600),
         (select id from public.networks where code = 'mtn'),
         115.00, 98.00, 'delivered',
         'VP-260724-EFMV', 'REM-89364458',
         '{"driver":"remadata","order_id":"REM-89364458","status":"success","network":"mtn","size_mb":25600,"phone":"0242248702"}'::jsonb,
         2,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-24T06:25:09.657Z', '2026-07-24T06:27:55.444Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260714-3308', '0551356793',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 25600),
         (select id from public.networks where code = 'mtn'),
         115.00, 98.00, 'delivered',
         'VP-260714-4366', 'REM-62347818',
         '{"driver":"remadata","order_id":"REM-62347818","status":"success","network":"mtn","size_mb":25600,"phone":"0551356793"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-14T19:07:41.865Z', '2026-07-14T19:12:22.572Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260720-3132', '0554076653',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 15360),
         (select id from public.networks where code = 'mtn'),
         75.00, 58.00, 'delivered',
         'VP-260720-B4K6', 'REM-18076477',
         '{"driver":"remadata","order_id":"REM-18076477","status":"success","network":"mtn","size_mb":15360,"phone":"0554076653"}'::jsonb,
         2,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-20T01:16:30.068Z', '2026-07-20T01:20:16.226Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260728-6690', '0241234567',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260728-Y4CF', 'REM-79603510',
         '{"driver":"remadata","order_id":"REM-79603510","status":"success","network":"telecel","size_mb":102400,"phone":"0241234567"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-28T16:54:10.281Z', '2026-07-28T16:56:53.622Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260804-1913', '0549948209',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 25600),
         (select id from public.networks where code = 'mtn'),
         115.00, 98.00, 'delivered',
         'VP-260804-JBZS', 'REM-88374300',
         '{"driver":"remadata","order_id":"REM-88374300","status":"success","network":"mtn","size_mb":25600,"phone":"0549948209"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-08-04T20:33:53.520Z', '2026-08-04T20:36:12.352Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260716-9122', '0256895672',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 25600),
         (select id from public.networks where code = 'mtn'),
         115.00, 98.00, 'failed',
         'VP-260716-QXUG', NULL,
         '{"ok":false,"error":"Provider gateway timeout (HTTP 504)","raw":{"driver":"mock","order":"VD-260716-9122"}}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-16T12:43:16.526Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-1264', '0209876543',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 10240),
         (select id from public.networks where code = 'airteltigo'),
         39.00, 35.50, 'delivered',
         'VP-260808-VW9C', 'REM-36560166',
         '{"driver":"remadata","order_id":"REM-36560166","status":"success","network":"airteltigo","size_mb":10240,"phone":"0209876543"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-08-08T12:13:34.558Z', '2026-08-08T12:14:44.178Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260717-2866', '0209876543',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260717-TXLG', 'REM-66727799',
         '{"driver":"remadata","order_id":"REM-66727799","status":"success","network":"telecel","size_mb":102400,"phone":"0209876543"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-07-17T12:46:56.543Z', '2026-07-17T12:51:36.397Z';

  -- bundle usage (one row per delivered order — powers usage tracking)
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260806-6799'), '0250812692',
         (select id from public.networks where code = 'mtn'),
         3072, 2500.10, 'active',
         '2026-08-06T11:09:04.942Z', NULL, '2026-08-06T21:45:19.432Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260729-7594'), '0209876543',
         (select id from public.networks where code = 'telecel'),
         30720, 23455.96, 'active',
         '2026-07-29T08:03:32.018Z', '2026-09-27T08:03:32.018Z', '2026-07-29T15:38:47.643Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-4884'), '0597066765',
         (select id from public.networks where code = 'mtn'),
         1024, 239.82, 'active',
         '2026-07-19T19:10:35.674Z', NULL, '2026-07-20T00:35:45.963Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260721-9488'), '0247788990',
         (select id from public.networks where code = 'telecel'),
         10240, 4812.82, 'active',
         '2026-07-21T09:18:46.987Z', '2026-09-19T09:18:46.987Z', '2026-07-22T00:50:23.721Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260720-3007'), '0266168899',
         (select id from public.networks where code = 'mtn'),
         8192, 6294.06, 'active',
         '2026-07-20T22:26:05.753Z', NULL, '2026-07-21T13:37:14.278Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260807-8219'), '0595499137',
         (select id from public.networks where code = 'mtn'),
         51200, 25760.83, 'active',
         '2026-08-07T01:24:40.159Z', NULL, '2026-08-07T10:14:00.887Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260721-1596'), '0501580260',
         (select id from public.networks where code = 'telecel'),
         102400, 30276.41, 'active',
         '2026-07-21T19:45:30.699Z', '2026-09-19T19:45:30.699Z', '2026-07-22T11:17:04.401Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260801-8223'), '0595948207',
         (select id from public.networks where code = 'mtn'),
         2048, 1577.36, 'active',
         '2026-08-01T13:58:19.948Z', NULL, '2026-08-01T20:15:25.369Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260715-5421'), '0590640104',
         (select id from public.networks where code = 'mtn'),
         20480, 10034.81, 'active',
         '2026-07-15T01:58:39.891Z', NULL, '2026-07-15T10:54:26.172Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260809-6077'), '0279039208',
         (select id from public.networks where code = 'airteltigo'),
         30720, 28338.90, 'active',
         '2026-08-09T13:05:24.680Z', '2026-10-08T13:05:24.680Z', '2026-08-09T19:20:26.437Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-2611'), '0247788990',
         (select id from public.networks where code = 'mtn'),
         8192, 657.09, 'active',
         '2026-08-08T06:50:42.760Z', NULL, '2026-08-08T23:28:07.827Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260807-5667'), '0550640824',
         (select id from public.networks where code = 'mtn'),
         5120, 2341.90, 'active',
         '2026-08-07T19:52:12.957Z', NULL, '2026-08-08T03:07:25.382Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-9029'), '0547000432',
         (select id from public.networks where code = 'mtn'),
         51200, 24781.94, 'active',
         '2026-07-19T04:32:17.435Z', NULL, '2026-07-20T01:22:15.145Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260802-8629'), '0269887748',
         (select id from public.networks where code = 'mtn'),
         2048, 1637.26, 'active',
         '2026-08-02T16:41:15.752Z', NULL, '2026-08-03T07:32:38.771Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260802-2030'), '0559988776',
         (select id from public.networks where code = 'mtn'),
         4096, 819.13, 'active',
         '2026-08-02T09:19:29.942Z', NULL, '2026-08-03T05:51:00.597Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260809-2083'), '0551112233',
         (select id from public.networks where code = 'mtn'),
         6144, 5579.23, 'active',
         '2026-08-09T00:29:00.289Z', NULL, '2026-08-09T12:18:12.790Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260727-2835'), '0596109346',
         (select id from public.networks where code = 'mtn'),
         1024, 411.92, 'active',
         '2026-07-27T07:10:12.782Z', NULL, '2026-07-28T04:33:15.888Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260731-2157'), '0561122334',
         (select id from public.networks where code = 'airteltigo'),
         10240, 2773.17, 'active',
         '2026-07-31T12:02:44.838Z', '2026-09-29T12:02:44.838Z', '2026-07-31T22:30:12.551Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260715-8214'), '0272292320',
         (select id from public.networks where code = 'airteltigo'),
         10240, 8724.81, 'active',
         '2026-07-15T07:34:44.525Z', '2026-09-13T07:34:44.525Z', '2026-07-16T03:42:17.839Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-5760'), '0559988776',
         (select id from public.networks where code = 'telecel'),
         10240, 5242.26, 'active',
         '2026-07-19T21:12:18.679Z', '2026-09-17T21:12:18.679Z', '2026-07-20T14:04:45.259Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260716-3458'), '0275346242',
         (select id from public.networks where code = 'airteltigo'),
         30720, 13032.86, 'active',
         '2026-07-16T02:27:10.328Z', '2026-09-14T02:27:10.328Z', '2026-07-16T19:57:49.649Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260804-5883'), '0247788990',
         (select id from public.networks where code = 'mtn'),
         5120, 3078.31, 'active',
         '2026-08-04T12:41:18.357Z', NULL, '2026-08-05T04:02:25.141Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260726-9728'), '0276655443',
         (select id from public.networks where code = 'mtn'),
         1024, 993.28, 'active',
         '2026-07-26T23:31:55.228Z', NULL, '2026-08-11T18:12:53.330Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260717-8085'), '0559988776',
         (select id from public.networks where code = 'telecel'),
         102400, 75290.59, 'active',
         '2026-07-17T06:24:22.346Z', '2026-09-15T06:24:22.346Z', '2026-07-17T12:51:22.425Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260731-6398'), '0263217842',
         (select id from public.networks where code = 'mtn'),
         10240, 2134.66, 'active',
         '2026-07-31T00:44:16.054Z', NULL, '2026-07-31T05:10:05.925Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260807-3982'), '0542245723',
         (select id from public.networks where code = 'mtn'),
         2048, 388.91, 'active',
         '2026-08-07T16:18:11.964Z', NULL, '2026-08-08T01:07:35.670Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260728-6616'), '0502345678',
         (select id from public.networks where code = 'mtn'),
         40960, 20695.77, 'active',
         '2026-07-28T09:41:03.340Z', NULL, '2026-07-29T02:18:00.105Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-6082'), '0561122334',
         (select id from public.networks where code = 'mtn'),
         3072, 1698.68, 'active',
         '2026-07-19T04:49:25.604Z', NULL, '2026-07-19T07:02:38.256Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260803-9502'), '0548612388',
         (select id from public.networks where code = 'mtn'),
         1024, 311.29, 'active',
         '2026-08-03T11:04:13.986Z', NULL, '2026-08-03T13:21:38.330Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260802-8856'), '0247788990',
         (select id from public.networks where code = 'mtn'),
         4096, 1348.98, 'active',
         '2026-08-02T00:20:10.668Z', NULL, '2026-08-02T02:42:37.336Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260731-1914'), '0201122334',
         (select id from public.networks where code = 'mtn'),
         2048, 1761.28, 'active',
         '2026-08-01T00:01:43.362Z', NULL, '2026-08-11T17:18:53.330Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260727-1989'), '0265373760',
         (select id from public.networks where code = 'mtn'),
         6144, 2734.83, 'active',
         '2026-07-27T21:09:35.781Z', NULL, '2026-07-27T23:25:06.921Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260717-9129'), '0273344556',
         (select id from public.networks where code = 'mtn'),
         6144, 2305.46, 'active',
         '2026-07-17T14:56:40.713Z', NULL, '2026-07-17T17:57:40.591Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-2399'), '0559988776',
         (select id from public.networks where code = 'mtn'),
         1024, 952.32, 'active',
         '2026-08-08T15:09:29.525Z', NULL, '2026-08-11T18:19:53.330Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260718-6521'), '0257679524',
         (select id from public.networks where code = 'mtn'),
         20480, 12859.49, 'active',
         '2026-07-18T08:36:14.842Z', NULL, '2026-07-19T05:21:34.425Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-5186'), '0241234567',
         (select id from public.networks where code = 'telecel'),
         10240, 5047.22, 'active',
         '2026-07-19T19:48:47.325Z', '2026-09-17T19:48:47.325Z', '2026-07-19T22:02:26.681Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260806-1699'), '0558491498',
         (select id from public.networks where code = 'mtn'),
         10240, 3857.72, 'active',
         '2026-08-06T11:30:20.226Z', NULL, '2026-08-06T20:32:58.020Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260724-6374'), '0242248702',
         (select id from public.networks where code = 'mtn'),
         25600, 22958.47, 'active',
         '2026-07-24T06:27:55.444Z', NULL, '2026-07-24T09:35:03.002Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260714-3308'), '0551356793',
         (select id from public.networks where code = 'mtn'),
         25600, 13693.87, 'active',
         '2026-07-14T19:12:22.572Z', NULL, '2026-07-15T07:38:39.134Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260720-3132'), '0554076653',
         (select id from public.networks where code = 'mtn'),
         15360, 12265.04, 'active',
         '2026-07-20T01:20:16.226Z', NULL, '2026-07-20T05:24:52.040Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260728-6690'), '0241234567',
         (select id from public.networks where code = 'telecel'),
         102400, 99328.00, 'active',
         '2026-07-28T16:56:53.622Z', '2026-09-26T16:56:53.622Z', '2026-08-11T17:26:53.330Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260804-1913'), '0549948209',
         (select id from public.networks where code = 'mtn'),
         25600, 6174.13, 'active',
         '2026-08-04T20:36:12.352Z', NULL, '2026-08-05T03:54:15.292Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-1264'), '0209876543',
         (select id from public.networks where code = 'airteltigo'),
         10240, 4631.06, 'active',
         '2026-08-08T12:14:44.178Z', '2026-10-07T12:14:44.178Z', '2026-08-08T23:37:02.024Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260717-2866'), '0209876543',
         (select id from public.networks where code = 'telecel'),
         102400, 85153.53, 'active',
         '2026-07-17T12:51:36.397Z', '2026-09-15T12:51:36.397Z', '2026-07-18T03:19:37.992Z';

  -- auto-reload opt-ins (explicit customer consent; relation = self|other)
  insert into public.auto_reload (customer_id, phone, relation, network_id, bundle_id, trigger_percent, momo_number, active, reload_count, last_reload_at, last_triggered_at, cooldown_until, created_at, updated_at)
  select (select id from public.customers where phone = '0241234567'), '0241234567', 'self',
         (select id from public.networks where code = 'mtn'),
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         10, '0245678901', true, 3,
         '2026-08-09T19:20:53.330Z', NULL,
         '2026-08-11T16:40:53.330Z', '2026-07-28T19:42:53.330Z', '2026-07-28T19:42:53.330Z';
  insert into public.auto_reload (customer_id, phone, relation, network_id, bundle_id, trigger_percent, momo_number, active, reload_count, last_reload_at, last_triggered_at, cooldown_until, created_at, updated_at)
  select (select id from public.customers where phone = '0209876543'), '0201122334', 'other',
         (select id from public.networks where code = 'telecel'),
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         20, '0505566778', true, 1,
         '2026-08-05T19:10:53.330Z', NULL,
         '2026-08-12T00:40:53.330Z', '2026-07-31T20:28:53.330Z', '2026-07-31T20:28:53.330Z';
  insert into public.auto_reload (customer_id, phone, relation, network_id, bundle_id, trigger_percent, momo_number, active, reload_count, last_reload_at, last_triggered_at, cooldown_until, created_at, updated_at)
  select (select id from public.customers where phone = '0502345678'), '0276655443', 'other',
         (select id from public.networks where code = 'airteltigo'),
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 1024),
         15, '0501234321', false, 2,
         '2026-08-02T20:40:53.330Z', NULL,
         NULL, '2026-08-03T18:56:53.330Z', '2026-08-03T18:56:53.330Z';

  -- float ledger (chronological; balance_after chained per network)
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'topup', 3000.00, 3000.00,
         NULL,
         'Initial float (demo seed)', '2026-07-10T19:22:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'topup', 2000.00, 2000.00,
         NULL,
         'Initial float (demo seed)', '2026-07-10T21:14:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'topup', 1500.00, 1500.00,
         NULL,
         'Initial float (demo seed)', '2026-07-10T23:39:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 98.00, 2902.00,
         (select id from public.orders where reference = 'VD-260714-3308'),
         'Delivery cost', '2026-07-14T19:09:41.865Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 73.00, 2829.00,
         (select id from public.orders where reference = 'VD-260715-5421'),
         'Delivery cost', '2026-07-15T01:57:24.653Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 35.50, 1464.50,
         (select id from public.orders where reference = 'VD-260715-8214'),
         'Delivery cost', '2026-07-15T07:34:36.341Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 106.00, 1358.50,
         (select id from public.orders where reference = 'VD-260716-3458'),
         'Delivery cost', '2026-07-16T02:25:56.274Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 1633.00,
         (select id from public.orders where reference = 'VD-260717-8085'),
         'Delivery cost', '2026-07-17T06:23:01.949Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 1266.00,
         (select id from public.orders where reference = 'VD-260717-2866'),
         'Delivery cost', '2026-07-17T12:48:56.543Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 24.50, 2804.50,
         (select id from public.orders where reference = 'VD-260717-9129'),
         'Delivery cost', '2026-07-17T14:55:00.127Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 73.00, 2731.50,
         (select id from public.orders where reference = 'VD-260718-6521'),
         'Delivery cost', '2026-07-18T08:34:28.113Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 185.00, 2546.50,
         (select id from public.orders where reference = 'VD-260719-9029'),
         'Delivery cost', '2026-07-19T04:30:08.636Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 11.90, 2534.60,
         (select id from public.orders where reference = 'VD-260719-6082'),
         'Delivery cost', '2026-07-19T04:49:38.622Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 2530.70,
         (select id from public.orders where reference = 'VD-260719-4884'),
         'Delivery cost', '2026-07-19T19:09:32.395Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 35.50, 1230.50,
         (select id from public.orders where reference = 'VD-260719-5186'),
         'Delivery cost', '2026-07-19T19:48:28.677Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 35.50, 1195.00,
         (select id from public.orders where reference = 'VD-260719-5760'),
         'Delivery cost', '2026-07-19T21:10:40.652Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 58.00, 2472.70,
         (select id from public.orders where reference = 'VD-260720-3132'),
         'Delivery cost', '2026-07-20T01:18:30.068Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 32.60, 2440.10,
         (select id from public.orders where reference = 'VD-260720-3007'),
         'Delivery cost', '2026-07-20T22:24:57.886Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 35.50, 1159.50,
         (select id from public.orders where reference = 'VD-260721-9488'),
         'Delivery cost', '2026-07-21T09:15:51.787Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'topup', 1000.00, 3440.10,
         NULL,
         'Restock — MTN float', '2026-07-21T19:02:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 792.50,
         (select id from public.orders where reference = 'VD-260721-1596'),
         'Delivery cost', '2026-07-21T19:42:32.071Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 98.00, 3342.10,
         (select id from public.orders where reference = 'VD-260724-6374'),
         'Delivery cost', '2026-07-24T06:27:09.657Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 3338.20,
         (select id from public.orders where reference = 'VD-260726-9728'),
         'Delivery cost', '2026-07-26T23:32:06.299Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 3334.30,
         (select id from public.orders where reference = 'VD-260727-2835'),
         'Delivery cost', '2026-07-27T07:10:37.791Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 24.50, 3309.80,
         (select id from public.orders where reference = 'VD-260727-1989'),
         'Delivery cost', '2026-07-27T21:09:21.823Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 159.00, 3150.80,
         (select id from public.orders where reference = 'VD-260728-6616'),
         'Delivery cost', '2026-07-28T09:40:05.156Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 425.50,
         (select id from public.orders where reference = 'VD-260728-6690'),
         'Delivery cost', '2026-07-28T16:56:10.281Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'topup', 800.00, 1225.50,
         NULL,
         'Restock — Telecel float', '2026-07-28T23:28:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 98.70, 1126.80,
         (select id from public.orders where reference = 'VD-260729-7594'),
         'Delivery cost', '2026-07-29T08:03:51.445Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 38.50, 3112.30,
         (select id from public.orders where reference = 'VD-260731-6398'),
         'Delivery cost', '2026-07-31T00:41:51.117Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 35.50, 1323.00,
         (select id from public.orders where reference = 'VD-260731-2157'),
         'Delivery cost', '2026-07-31T12:01:19.479Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 3104.20,
         (select id from public.orders where reference = 'VD-260731-1914'),
         'Delivery cost', '2026-07-31T23:59:56.829Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 3096.10,
         (select id from public.orders where reference = 'VD-260801-8223'),
         'Delivery cost', '2026-08-01T13:57:58.626Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 16.60, 3079.50,
         (select id from public.orders where reference = 'VD-260802-8856'),
         'Delivery cost', '2026-08-02T00:18:20.344Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 16.60, 3062.90,
         (select id from public.orders where reference = 'VD-260802-2030'),
         'Delivery cost', '2026-08-02T09:19:58.222Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 3054.80,
         (select id from public.orders where reference = 'VD-260802-8629'),
         'Delivery cost', '2026-08-02T16:39:23.412Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'topup', 600.00, 1923.00,
         NULL,
         'Restock — AirtelTigo float', '2026-08-02T20:24:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 3050.90,
         (select id from public.orders where reference = 'VD-260803-9502'),
         'Delivery cost', '2026-08-03T11:04:26.613Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 18.90, 3032.00,
         (select id from public.orders where reference = 'VD-260804-5883'),
         'Delivery cost', '2026-08-04T12:39:01.105Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 98.00, 2934.00,
         (select id from public.orders where reference = 'VD-260804-1913'),
         'Delivery cost', '2026-08-04T20:35:53.520Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 11.90, 2922.10,
         (select id from public.orders where reference = 'VD-260806-6799'),
         'Delivery cost', '2026-08-06T11:08:44.986Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 38.50, 2883.60,
         (select id from public.orders where reference = 'VD-260806-1699'),
         'Delivery cost', '2026-08-06T11:28:50.105Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 185.00, 2698.60,
         (select id from public.orders where reference = 'VD-260807-8219'),
         'Delivery cost', '2026-08-07T01:25:35.734Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 2690.50,
         (select id from public.orders where reference = 'VD-260807-3982'),
         'Delivery cost', '2026-08-07T16:18:50.828Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 18.90, 2671.60,
         (select id from public.orders where reference = 'VD-260807-5667'),
         'Delivery cost', '2026-08-07T19:50:18.722Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'topup', 500.00, 3171.60,
         NULL,
         'Restock — MTN float', '2026-08-07T22:07:53.330Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 32.60, 3139.00,
         (select id from public.orders where reference = 'VD-260808-2611'),
         'Delivery cost', '2026-08-08T06:48:27.769Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 35.50, 1887.50,
         (select id from public.orders where reference = 'VD-260808-1264'),
         'Delivery cost', '2026-08-08T12:15:34.558Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 3135.10,
         (select id from public.orders where reference = 'VD-260808-2399'),
         'Delivery cost', '2026-08-08T15:08:49.168Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 24.50, 3110.60,
         (select id from public.orders where reference = 'VD-260809-2083'),
         'Delivery cost', '2026-08-09T00:27:47.300Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 106.00, 1781.50,
         (select id from public.orders where reference = 'VD-260809-6077'),
         'Delivery cost', '2026-08-09T13:04:50.884Z';

  -- audit log (forged callbacks & unknown-order entries included on purpose)
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260714-4366","reference":"VD-260714-3308","amount":115,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-14T19:10:16.976Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260715-RM7J","reference":"VD-260715-5421","amount":93,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-15T02:01:18.192Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260715-DENA","reference":"VD-260715-8214","amount":39,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-15T07:36:31.961Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260715-F3VS","reference":"VD-260715-7057","amount":17,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-15T14:59:07.956Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260716-Q73K","reference":"VD-260716-3458","amount":117,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-16T02:27:16.953Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260716-QXUG","reference":"VD-260716-9122","amount":115,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-16T12:47:49.106Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260717-6G94","reference":"VD-260717-8085","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-17T06:26:59.828Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260717-TXLG","reference":"VD-260717-2866","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-17T12:49:26.695Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260717-LKLL","reference":"VD-260717-9129","amount":35,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-17T14:55:40.120Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260718-8CDL","reference":"VD-260718-6521","amount":93,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-18T08:37:02.183Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-SYQ7","reference":"VD-260719-9029","amount":220,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T04:33:12.195Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-SEFJ","reference":"VD-260719-6082","amount":17,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T04:52:20.381Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-YWN8","reference":"VD-260719-4884","amount":6,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T19:12:20.784Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-4G2T","reference":"VD-260719-5186","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T19:51:31.691Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-AY27","reference":"VD-260719-5760","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T21:10:42.831Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260720-B4K6","reference":"VD-260720-3132","amount":75,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-20T01:20:29.972Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260720-2H3S","reference":"VD-260720-3007","amount":43,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-20T22:26:10.234Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260721-YCXQ","reference":"VD-260721-9488","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-21T09:17:47.777Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260721-GJYS","reference":"VD-260721-1596","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-21T19:45:22.920Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260724-EFMV","reference":"VD-260724-6374","amount":115,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-24T06:28:55.258Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260726-S3Y9","reference":"VD-260726-9728","amount":6,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-26T23:34:50.033Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260727-8KUQ","reference":"VD-260727-2835","amount":6,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-27T07:13:56.134Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260727-L7JC","reference":"VD-260727-1989","amount":35,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-27T21:12:06.008Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260728-PY9V","reference":"VD-260728-6616","amount":180,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-28T09:40:14.517Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260728-Y4CF","reference":"VD-260728-6690","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-28T16:58:13.389Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260728-TTFX","reference":"VD-260728-3783","amount":19.9,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-28T18:00:58.498Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260729-32J9","reference":"VD-260729-7594","amount":110,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-29T08:06:27.661Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260731-HU34","reference":"VD-260731-6398","amount":52,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-31T00:43:55.206Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260731-CLVP","reference":"VD-260731-2157","amount":39,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-31T12:02:20.470Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260731-XC9N","reference":"VD-260731-1914","amount":12,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-01T00:00:08.925Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260801-WK5G","reference":"VD-260801-8223","amount":12,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-01T14:01:46.067Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260802-B6RB","reference":"VD-260802-8856","amount":23,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-02T00:18:49.022Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260802-4VR3","reference":"VD-260802-2030","amount":23,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-02T09:22:24.022Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260802-V3VV","reference":"VD-260802-8629","amount":12,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-02T16:42:48.750Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260803-R8FU","reference":"VD-260803-9502","amount":6,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-03T11:07:48.574Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.failed","provider_reference":"VP-260803-FFFF","reference":"VD-260803-0000","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-03T22:22:53.330Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260804-QXY3","reference":"VD-260804-5883","amount":28,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-04T12:42:23.735Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260804-CT8W","reference":"VD-260804-2384","amount":52,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-04T20:21:31.386Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260804-JBZS","reference":"VD-260804-1913","amount":115,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-04T20:36:40.057Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260805-ZZZZ","reference":"VD-260805-0000","amount":19.9,"currency":"GHS"}'::jsonb, true, 'unknown order VD-260805-0000', '2026-08-05T22:25:53.330Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260806-MDFU","reference":"VD-260806-6799","amount":17,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-06T11:11:19.007Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260806-9M5L","reference":"VD-260806-1699","amount":52,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-06T11:29:20.544Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260807-TBQH","reference":"VD-260807-8219","amount":220,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-07T01:27:08.251Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260807-JH2W","reference":"VD-260807-3982","amount":12,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-07T16:20:52.224Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260807-H7LM","reference":"VD-260807-5667","amount":28,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-07T19:53:48.741Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-UQS2","reference":"VD-260808-2611","amount":43,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T06:49:33.165Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-VW9C","reference":"VD-260808-1264","amount":39,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T12:19:02.055Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-FBE4","reference":"VD-260808-2399","amount":6,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T15:12:39.453Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-AH6A","reference":"VD-260808-5150","amount":117,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T20:02:11.089Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (false, '{"event":"payment.succeeded","provider_reference":"VP-TEST-FORGED1","reference":"VD-260808-0000","amount":43,"currency":"GHS"}'::jsonb, true, 'invalid signature', '2026-08-08T20:26:53.330Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260809-J63L","reference":"VD-260809-2083","amount":35,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-09T00:29:55.340Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260809-N9VC","reference":"VD-260809-4475","amount":405,"currency":"GHS"}'::jsonb, true, 'amount mismatch → refunded', '2026-08-09T07:26:57.852Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260809-MVK5","reference":"VD-260809-6077","amount":117,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-09T13:06:11.195Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (false, '{"event":"payment.succeeded","provider_reference":"VP-TEST-FORGED2","reference":"VD-260809-0000","amount":9,"currency":"GHS"}'::jsonb, true, 'invalid signature', '2026-08-09T22:16:53.330Z');

  raise notice 'Valmont Data demo seed complete: % customers, % saved numbers, % orders, % usage rows, % auto-reload rules, % float entries, % webhook logs (final float: MTN %, Telecel %, AirtelTigo %).',
    5, 16, 52, 44, 3, 51, 54,
    3110.60, 1126.80, 1781.50;
end $$;
