-- ============================================================================
-- VALMONT DATA — demo seed (customers, saved numbers, orders, bundle usage,
-- auto-reload opt-ins, float, webhooks)
-- Generated by : node scripts/seed-demo.js --sql   (edit lib/demo-data.js and re-run,
--                never hand-edit this file)
-- Anchored to  : 2026-08-11T15:43:49.270Z
-- Environment  : DEMO / STAGING Supabase ONLY — do not run against production.
-- Safe to re-run: skips itself when public.orders already has rows.
-- Demo logins  : PIN 1234 → 0241234567 (Ama Serwaa), 0209876543 (Kofi Mensah), 0551112233 (Abena Owusu), 0502345678 (Yaw Boateng), 0273344556 (Esi Asante)
-- ============================================================================

do $$
begin
  if exists (select 1 from public.orders) then
    raise notice 'Valmont Data demo seed SKIPPED — orders table is not empty.';
    return;
  end if;

  -- demo customer accounts (scrypt pin_hash; PINs listed in the header)
  insert into public.customers (phone, email, name, pin_hash, created_at) values
    ('0241234567', 'ama.serwaa@example.com', 'Ama Serwaa', '43d593ef1d3d7f9d4386cd27b199fa71:3aed832fa6058065c5f3d4ae909e184048013e5c3d16dab88b1c43a16ecd31a0996288f6feaab149980f444a7b304766cbab8972f14121cbe28b324144834472', '2026-06-26T16:28:49.270Z'),
    ('0209876543', 'kofi.mensah@example.com', 'Kofi Mensah', 'fcf49feb43bdddf9a7c3c278adbd0877:7a4d2b30156a7c31622bcddc76d1972ed7738051b1647a5495f5e28ca6ec1f37e2ad1338f835b0bc77c3d56ba79fc5f0f5951c60b26254a67e1f284e7551eec4', '2026-06-30T16:04:49.270Z'),
    ('0551112233', 'abena.owusu@example.com', 'Abena Owusu', '60cb2886eb29a982267c6d1aa05788f4:e99c811843f9af5261c46e3c6e65b4b08b553bb34564f8c8365b40a2be8a23d6ffe750aae10f883daba34c773c08eb2026c327cd9c986e59fcb624b175d88936', '2026-07-04T17:14:49.270Z'),
    ('0502345678', 'yaw.boateng@example.com', 'Yaw Boateng', '8838d820a4c5f7993beeff8f548ab889:d4634b9757c78d8216b0013118fd28f04164d8b167103ff5ab6a6e10a09393219bde5fad721e79b79105a87738fd8a95a600ac5ab25b93f8eff6344ba95344d4', '2026-07-08T16:04:49.270Z'),
    ('0273344556', 'esi.asante@example.com', 'Esi Asante', 'f02d610699fe423731dff7310b5c79db:cb52d542195386e8d690766c0709785775f99f30d918ba23351494410793659c4df6de4d9852a5ad520d9a0ac3a541175de74a468c541b503674263e50daf9f0', '2026-07-12T16:06:49.270Z')
  on conflict (phone) do nothing;

  -- saved data lines + MoMo numbers
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0241234567', 'My line', '2026-07-02T17:10:49.270Z' from public.customers where phone = '0241234567'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0559988776', 'Mum''s line', '2026-07-03T17:10:49.270Z' from public.customers where phone = '0241234567'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0245678901', 'My MoMo', '2026-07-04T17:39:49.270Z' from public.customers where phone = '0241234567'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0209876543', 'My line', '2026-07-05T17:55:49.270Z' from public.customers where phone = '0209876543'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0201122334', 'Shop line', '2026-07-06T18:37:49.270Z' from public.customers where phone = '0209876543'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0505566778', 'MoMo', '2026-07-07T15:46:49.270Z' from public.customers where phone = '0209876543'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0551112233', 'My line', '2026-07-08T18:36:49.270Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0247788990', 'Work line', '2026-07-09T18:14:49.270Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0559998877', 'MoMo', '2026-07-10T15:50:49.270Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0241212121', 'Dad''s MoMo', '2026-07-11T15:55:49.270Z' from public.customers where phone = '0551112233'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0502345678', 'My line', '2026-07-12T15:47:49.270Z' from public.customers where phone = '0502345678'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0276655443', 'Family line', '2026-07-13T18:14:49.270Z' from public.customers where phone = '0502345678'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0501234321', 'Business MoMo', '2026-07-14T16:26:49.270Z' from public.customers where phone = '0502345678'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0273344556', 'My line', '2026-07-15T16:23:49.270Z' from public.customers where phone = '0273344556'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'data', '0561122334', 'Brother''s line', '2026-07-16T17:47:49.270Z' from public.customers where phone = '0273344556'
  on conflict (customer_id, kind, phone) do nothing;
  insert into public.saved_numbers (customer_id, kind, phone, label, created_at)
  select id, 'momo', '0277788990', 'MoMo', '2026-07-17T18:27:49.270Z' from public.customers where phone = '0273344556'
  on conflict (customer_id, kind, phone) do nothing;

  -- orders (bundle/network/customer ids resolved from the base seed)
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260806-6799', '0250812692',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         9.00, 8.10, 'delivered',
         'VP-260806-MDFU', 'REM-80322636',
         '{"driver":"remadata","order_id":"REM-80322636","status":"success","network":"mtn","size_mb":2048,"phone":"0250812692"}'::jsonb,
         1,
         NULL,
         '2026-08-06T08:09:40.926Z', '2026-08-06T08:12:00.882Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260729-7594', '0209876543',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 30720),
         (select id from public.networks where code = 'telecel'),
         110.00, 98.70, 'delivered',
         'VP-260729-32J9', 'REM-99359595',
         '{"driver":"remadata","order_id":"REM-99359595","status":"success","network":"telecel","size_mb":30720,"phone":"0209876543"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-07-29T05:04:47.385Z', '2026-07-29T05:06:27.958Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-5150', '0271137953',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 30720),
         (select id from public.networks where code = 'airteltigo'),
         117.00, 106.00, 'failed',
         'VP-260808-AH6A', NULL,
         '{"ok":false,"error":"Supplier API error: SUBSCRIBER_NOT_FOUND","raw":{"driver":"mock","order":"VD-260808-5150"}}'::jsonb,
         1,
         NULL,
         '2026-08-08T17:02:42.825Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-4884', '0597066765',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         4.20, 3.90, 'delivered',
         'VP-260719-YWN8', 'REM-15431188',
         '{"driver":"remadata","order_id":"REM-15431188","status":"success","network":"mtn","size_mb":1024,"phone":"0597066765"}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-19T16:10:28.335Z', '2026-07-19T16:13:31.614Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260721-9488', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         (select id from public.networks where code = 'telecel'),
         39.50, 35.50, 'delivered',
         'VP-260721-YCXQ', 'REM-94503305',
         '{"driver":"remadata","order_id":"REM-94503305","status":"success","network":"telecel","size_mb":10240,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-07-21T06:16:47.727Z', '2026-07-21T06:21:42.927Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260720-3007', '0266168899',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 10240),
         (select id from public.networks where code = 'mtn'),
         43.00, 38.50, 'delivered',
         'VP-260720-2H3S', 'REM-10770728',
         '{"driver":"remadata","order_id":"REM-10770728","status":"success","network":"mtn","size_mb":10240,"phone":"0266168899"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-07-20T19:25:53.826Z', '2026-07-20T19:29:01.693Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260806-8219', '0595499137',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 102400),
         (select id from public.networks where code = 'mtn'),
         407.00, 377.00, 'delivered',
         'VP-260806-TBQH', 'REM-51912483',
         '{"driver":"remadata","order_id":"REM-51912483","status":"success","network":"mtn","size_mb":102400,"phone":"0595499137"}'::jsonb,
         1,
         NULL,
         '2026-08-06T22:26:31.674Z', '2026-08-06T22:27:36.099Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260721-1596', '0501580260',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260721-GJYS', 'REM-16353422',
         '{"driver":"remadata","order_id":"REM-16353422","status":"success","network":"telecel","size_mb":102400,"phone":"0501580260"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-21T16:43:28.011Z', '2026-07-21T16:48:26.639Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260801-8223', '0595948207',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         9.00, 8.10, 'delivered',
         'VP-260801-WK5G', 'REM-12541517',
         '{"driver":"remadata","order_id":"REM-12541517","status":"success","network":"mtn","size_mb":2048,"phone":"0595948207"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-08-01T10:58:54.566Z', '2026-08-01T11:01:15.888Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260714-5421', '0590640104',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 30720),
         (select id from public.networks where code = 'mtn'),
         125.00, 111.00, 'delivered',
         'VP-260714-RM7J', 'REM-51423657',
         '{"driver":"remadata","order_id":"REM-51423657","status":"success","network":"mtn","size_mb":30720,"phone":"0590640104"}'::jsonb,
         1,
         NULL,
         '2026-07-14T22:58:20.593Z', '2026-07-14T23:01:35.831Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260809-6077', '0279039208',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 30720),
         (select id from public.networks where code = 'airteltigo'),
         117.00, 106.00, 'delivered',
         'VP-260809-MVK5', 'REM-63109304',
         '{"driver":"remadata","order_id":"REM-63109304","status":"success","network":"airteltigo","size_mb":30720,"phone":"0279039208"}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-08-09T10:05:46.824Z', '2026-08-09T10:08:20.620Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-2611', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 10240),
         (select id from public.networks where code = 'mtn'),
         43.00, 38.50, 'delivered',
         'VP-260808-UQS2', 'REM-10406868',
         '{"driver":"remadata","order_id":"REM-10406868","status":"success","network":"mtn","size_mb":10240,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-08T03:49:23.709Z', '2026-08-08T03:53:38.700Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-5667', '0550640824',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         13.50, 11.90, 'delivered',
         'VP-260807-H7LM', 'REM-73268060',
         '{"driver":"remadata","order_id":"REM-73268060","status":"success","network":"mtn","size_mb":3072,"phone":"0550640824"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-07T16:51:14.662Z', '2026-08-07T16:55:08.897Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-9029', '0547000432',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 102400),
         (select id from public.networks where code = 'mtn'),
         407.00, 377.00, 'delivered',
         'VP-260719-SYQ7', 'REM-17377712',
         '{"driver":"remadata","order_id":"REM-17377712","status":"success","network":"mtn","size_mb":102400,"phone":"0547000432"}'::jsonb,
         1,
         NULL,
         '2026-07-19T01:31:04.576Z', '2026-07-19T01:35:13.375Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260802-8629', '0269887748',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         4.20, 3.90, 'delivered',
         'VP-260802-V3VV', 'REM-16246847',
         '{"driver":"remadata","order_id":"REM-16246847","status":"success","network":"mtn","size_mb":1024,"phone":"0269887748"}'::jsonb,
         1,
         NULL,
         '2026-08-02T13:40:19.352Z', '2026-08-02T13:44:11.692Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260802-2030', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         13.50, 11.90, 'delivered',
         'VP-260802-4VR3', 'REM-48044253',
         '{"driver":"remadata","order_id":"REM-48044253","status":"success","network":"mtn","size_mb":3072,"phone":"0559988776"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-08-02T06:20:54.162Z', '2026-08-02T06:22:25.882Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-2083', '0551112233',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         20.50, 18.90, 'delivered',
         'VP-260808-J63L', 'REM-31286903',
         '{"driver":"remadata","order_id":"REM-31286903","status":"success","network":"mtn","size_mb":5120,"phone":"0551112233"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-08T21:28:43.240Z', '2026-08-08T21:31:56.229Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260727-2835', '0596109346',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         4.20, 3.90, 'delivered',
         'VP-260727-8KUQ', 'REM-62798147',
         '{"driver":"remadata","order_id":"REM-62798147","status":"success","network":"mtn","size_mb":1024,"phone":"0596109346"}'::jsonb,
         1,
         NULL,
         '2026-07-27T04:11:33.731Z', '2026-07-27T04:13:08.722Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260731-2157', '0561122334',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 10240),
         (select id from public.networks where code = 'airteltigo'),
         39.00, 35.50, 'delivered',
         'VP-260731-CLVP', 'REM-26827162',
         '{"driver":"remadata","order_id":"REM-26827162","status":"success","network":"airteltigo","size_mb":10240,"phone":"0561122334"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-31T09:02:15.419Z', '2026-07-31T09:05:40.778Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-6770', '0266199330',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         13.50, 11.90, 'pending',
         NULL, NULL,
         NULL,
         0,
         (select id from public.customers where phone = '0273344556'),
         '2026-08-07T14:28:20.878Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260804-2384', '0257013265',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 20480),
         (select id from public.networks where code = 'mtn'),
         82.00, 73.00, 'delivering',
         'VP-260804-CT8W', NULL,
         NULL,
         1,
         NULL,
         '2026-08-04T17:20:30.697Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260809-4475', '0551112233',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'refunded',
         'VP-260809-N9VC', NULL,
         '{"refunded":true,"reason":"Amount mismatch: webhook 415.00 vs order 405.00"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-09T04:24:24.330Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260715-8214', '0272292320',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 10240),
         (select id from public.networks where code = 'airteltigo'),
         39.00, 35.50, 'delivered',
         'VP-260715-DENA', 'REM-92924717',
         '{"driver":"remadata","order_id":"REM-92924717","status":"success","network":"airteltigo","size_mb":10240,"phone":"0272292320"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-15T04:35:32.281Z', '2026-07-15T04:37:40.465Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-5760', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         (select id from public.networks where code = 'telecel'),
         39.50, 35.50, 'delivered',
         'VP-260719-AY27', 'REM-43632377',
         '{"driver":"remadata","order_id":"REM-43632377","status":"success","network":"telecel","size_mb":10240,"phone":"0559988776"}'::jsonb,
         2,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-19T18:11:36.592Z', '2026-07-19T18:15:14.619Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260715-3458', '0275346242',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 30720),
         (select id from public.networks where code = 'airteltigo'),
         117.00, 106.00, 'delivered',
         'VP-260715-Q73K', 'REM-87025588',
         '{"driver":"remadata","order_id":"REM-87025588","status":"success","network":"airteltigo","size_mb":30720,"phone":"0275346242"}'::jsonb,
         1,
         NULL,
         '2026-07-15T23:26:52.214Z', '2026-07-15T23:30:06.268Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260804-5883', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         13.50, 11.90, 'delivered',
         'VP-260804-QXY3', 'REM-93275626',
         '{"driver":"remadata","order_id":"REM-93275626","status":"success","network":"mtn","size_mb":3072,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-04T09:39:57.045Z', '2026-08-04T09:44:14.297Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260728-3783', '0569485282',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 5120),
         (select id from public.networks where code = 'airteltigo'),
         19.90, 18.00, 'delivering',
         'VP-260728-TTFX', NULL,
         NULL,
         1,
         NULL,
         '2026-07-28T14:58:32.858Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260727-3210', '0502345678',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         13.50, 11.90, 'pending',
         NULL, NULL,
         NULL,
         0,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-27T13:03:06.105Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260726-9728', '0276655443',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         4.20, 3.90, 'delivered',
         'VP-260726-S3Y9', 'REM-93529305',
         '{"driver":"remadata","order_id":"REM-93529305","status":"success","network":"mtn","size_mb":1024,"phone":"0276655443"}'::jsonb,
         2,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-26T20:33:02.239Z', '2026-07-26T20:34:51.168Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260717-8085', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260717-6G94', 'REM-37729123',
         '{"driver":"remadata","order_id":"REM-37729123","status":"success","network":"telecel","size_mb":102400,"phone":"0559988776"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-17T03:23:57.889Z', '2026-07-17T03:27:18.286Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260730-6398', '0263217842',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 10240),
         (select id from public.networks where code = 'mtn'),
         43.00, 38.50, 'delivered',
         'VP-260730-HU34', 'REM-99106254',
         '{"driver":"remadata","order_id":"REM-99106254","status":"success","network":"mtn","size_mb":10240,"phone":"0263217842"}'::jsonb,
         1,
         NULL,
         '2026-07-30T21:42:47.057Z', '2026-07-30T21:47:11.994Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260807-3982', '0542245723',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         9.00, 8.10, 'delivered',
         'VP-260807-JH2W', 'REM-94735765',
         '{"driver":"remadata","order_id":"REM-94735765","status":"success","network":"mtn","size_mb":2048,"phone":"0542245723"}'::jsonb,
         2,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-07T13:19:46.768Z', '2026-08-07T13:21:07.904Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260715-7057', '0540982919',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         9.00, 8.10, 'failed',
         'VP-260715-F3VS', NULL,
         '{"ok":false,"error":"Invalid recipient — number cannot receive this bundle","raw":{"driver":"mock","order":"VD-260715-7057"}}'::jsonb,
         1,
         NULL,
         '2026-07-15T11:57:42.287Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260728-6616', '0502345678',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 102400),
         (select id from public.networks where code = 'mtn'),
         407.00, 377.00, 'delivered',
         'VP-260728-PY9V', 'REM-73067886',
         '{"driver":"remadata","order_id":"REM-73067886","status":"success","network":"mtn","size_mb":102400,"phone":"0502345678"}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-28T06:41:01.096Z', '2026-07-28T06:43:59.280Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-6082', '0561122334',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         9.00, 8.10, 'delivered',
         'VP-260719-SEFJ', 'REM-39715366',
         '{"driver":"remadata","order_id":"REM-39715366","status":"success","network":"mtn","size_mb":2048,"phone":"0561122334"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-19T01:50:34.562Z', '2026-07-19T01:52:21.544Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260803-9502', '0548612388',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         4.20, 3.90, 'delivered',
         'VP-260803-R8FU', 'REM-88756896',
         '{"driver":"remadata","order_id":"REM-88756896","status":"success","network":"mtn","size_mb":1024,"phone":"0548612388"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-08-03T08:05:22.553Z', '2026-08-03T08:07:09.926Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260801-8856', '0247788990',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 3072),
         (select id from public.networks where code = 'mtn'),
         13.50, 11.90, 'delivered',
         'VP-260801-B6RB', 'REM-54616799',
         '{"driver":"remadata","order_id":"REM-54616799","status":"success","network":"mtn","size_mb":3072,"phone":"0247788990"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-01T21:19:16.284Z', '2026-08-01T21:23:06.608Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260731-1914', '0201122334',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 2048),
         (select id from public.networks where code = 'mtn'),
         9.00, 8.10, 'delivered',
         'VP-260731-XC9N', 'REM-23655494',
         '{"driver":"remadata","order_id":"REM-23655494","status":"success","network":"mtn","size_mb":2048,"phone":"0201122334"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-07-31T21:00:52.769Z', '2026-07-31T21:04:39.302Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260727-1989', '0265373760',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         20.50, 18.90, 'delivered',
         'VP-260727-L7JC', 'REM-30801831',
         '{"driver":"remadata","order_id":"REM-30801831","status":"success","network":"mtn","size_mb":5120,"phone":"0265373760"}'::jsonb,
         2,
         NULL,
         '2026-07-27T18:10:17.763Z', '2026-07-27T18:12:31.721Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260717-9129', '0273344556',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 5120),
         (select id from public.networks where code = 'mtn'),
         20.50, 18.90, 'delivered',
         'VP-260717-LKLL', 'REM-21689291',
         '{"driver":"remadata","order_id":"REM-21689291","status":"success","network":"mtn","size_mb":5120,"phone":"0273344556"}'::jsonb,
         2,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-17T11:55:56.067Z', '2026-07-17T11:59:36.653Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-2399', '0559988776',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         (select id from public.networks where code = 'mtn'),
         4.20, 3.90, 'delivered',
         'VP-260808-FBE4', 'REM-22880886',
         '{"driver":"remadata","order_id":"REM-22880886","status":"success","network":"mtn","size_mb":1024,"phone":"0559988776"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-08-08T12:09:45.108Z', '2026-08-08T12:12:25.465Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260718-6521', '0257679524',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 30720),
         (select id from public.networks where code = 'mtn'),
         125.00, 111.00, 'delivered',
         'VP-260718-8CDL', 'REM-35137871',
         '{"driver":"remadata","order_id":"REM-35137871","status":"success","network":"mtn","size_mb":30720,"phone":"0257679524"}'::jsonb,
         2,
         NULL,
         '2026-07-18T05:35:24.053Z', '2026-07-18T05:39:10.782Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-5186', '0241234567',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         (select id from public.networks where code = 'telecel'),
         39.50, 35.50, 'delivered',
         'VP-260719-4G2T', 'REM-47348147',
         '{"driver":"remadata","order_id":"REM-47348147","status":"success","network":"telecel","size_mb":10240,"phone":"0241234567"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-19T16:49:24.617Z', '2026-07-19T16:51:43.265Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260806-1699', '0558491498',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 20480),
         (select id from public.networks where code = 'mtn'),
         82.00, 73.00, 'delivered',
         'VP-260806-9M5L', 'REM-47574191',
         '{"driver":"remadata","order_id":"REM-47574191","status":"success","network":"mtn","size_mb":20480,"phone":"0558491498"}'::jsonb,
         1,
         (select id from public.customers where phone = '0551112233'),
         '2026-08-06T08:29:46.045Z', '2026-08-06T08:33:16.166Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260724-6374', '0242248702',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 30720),
         (select id from public.networks where code = 'mtn'),
         125.00, 111.00, 'delivered',
         'VP-260724-EFMV', 'REM-89364458',
         '{"driver":"remadata","order_id":"REM-89364458","status":"success","network":"mtn","size_mb":30720,"phone":"0242248702"}'::jsonb,
         2,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-24T03:28:05.597Z', '2026-07-24T03:30:51.384Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260714-3308', '0551356793',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 30720),
         (select id from public.networks where code = 'mtn'),
         125.00, 111.00, 'delivered',
         'VP-260714-4366', 'REM-62347818',
         '{"driver":"remadata","order_id":"REM-62347818","status":"success","network":"mtn","size_mb":30720,"phone":"0551356793"}'::jsonb,
         1,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-14T16:10:37.805Z', '2026-07-14T16:15:18.512Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260719-3132', '0554076653',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 20480),
         (select id from public.networks where code = 'mtn'),
         82.00, 73.00, 'delivered',
         'VP-260719-B4K6', 'REM-18076477',
         '{"driver":"remadata","order_id":"REM-18076477","status":"success","network":"mtn","size_mb":20480,"phone":"0554076653"}'::jsonb,
         2,
         (select id from public.customers where phone = '0273344556'),
         '2026-07-19T22:19:26.008Z', '2026-07-19T22:23:12.166Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260728-6690', '0241234567',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260728-Y4CF', 'REM-79603510',
         '{"driver":"remadata","order_id":"REM-79603510","status":"success","network":"telecel","size_mb":102400,"phone":"0241234567"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-07-28T13:57:06.221Z', '2026-07-28T13:59:49.562Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260804-1913', '0549948209',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 30720),
         (select id from public.networks where code = 'mtn'),
         125.00, 111.00, 'delivered',
         'VP-260804-JBZS', 'REM-88374300',
         '{"driver":"remadata","order_id":"REM-88374300","status":"success","network":"mtn","size_mb":30720,"phone":"0549948209"}'::jsonb,
         1,
         (select id from public.customers where phone = '0241234567'),
         '2026-08-04T17:36:49.460Z', '2026-08-04T17:39:08.292Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260716-9122', '0256895672',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 30720),
         (select id from public.networks where code = 'mtn'),
         125.00, 111.00, 'failed',
         'VP-260716-QXUG', NULL,
         '{"ok":false,"error":"Provider gateway timeout (HTTP 504)","raw":{"driver":"mock","order":"VD-260716-9122"}}'::jsonb,
         1,
         (select id from public.customers where phone = '0502345678'),
         '2026-07-16T09:46:12.466Z', NULL;
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260808-1264', '0209876543',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 10240),
         (select id from public.networks where code = 'airteltigo'),
         39.00, 35.50, 'delivered',
         'VP-260808-VW9C', 'REM-36560166',
         '{"driver":"remadata","order_id":"REM-36560166","status":"success","network":"airteltigo","size_mb":10240,"phone":"0209876543"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-08-08T09:16:30.498Z', '2026-08-08T09:17:40.118Z';
  insert into public.orders (reference, phone, bundle_id, network_id, amount, cost_price, status, provider_reference, supplier_ref, supplier_response, attempts, customer_id, created_at, delivered_at)
  select 'VD-260717-2866', '0209876543',
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 102400),
         (select id from public.networks where code = 'telecel'),
         405.00, 367.00, 'delivered',
         'VP-260717-TXLG', 'REM-66727799',
         '{"driver":"remadata","order_id":"REM-66727799","status":"success","network":"telecel","size_mb":102400,"phone":"0209876543"}'::jsonb,
         1,
         (select id from public.customers where phone = '0209876543'),
         '2026-07-17T09:49:52.483Z', '2026-07-17T09:54:32.337Z';

  -- bundle usage (one row per delivered order — powers usage tracking)
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260806-6799'), '0250812692',
         (select id from public.networks where code = 'mtn'),
         2048, 1666.73, 'active',
         '2026-08-06T08:12:00.882Z', NULL, '2026-08-06T18:48:15.372Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260729-7594'), '0209876543',
         (select id from public.networks where code = 'telecel'),
         30720, 23455.96, 'active',
         '2026-07-29T05:06:27.958Z', '2026-09-27T05:06:27.958Z', '2026-07-29T12:41:43.583Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-4884'), '0597066765',
         (select id from public.networks where code = 'mtn'),
         1024, 239.82, 'active',
         '2026-07-19T16:13:31.614Z', NULL, '2026-07-19T21:38:41.903Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260721-9488'), '0247788990',
         (select id from public.networks where code = 'telecel'),
         10240, 4812.82, 'active',
         '2026-07-21T06:21:42.927Z', '2026-09-19T06:21:42.927Z', '2026-07-21T21:53:19.661Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260720-3007'), '0266168899',
         (select id from public.networks where code = 'mtn'),
         10240, 7867.58, 'active',
         '2026-07-20T19:29:01.693Z', NULL, '2026-07-21T10:40:10.218Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260806-8219'), '0595499137',
         (select id from public.networks where code = 'mtn'),
         102400, 51521.66, 'active',
         '2026-08-06T22:27:36.099Z', NULL, '2026-08-07T07:16:56.827Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260721-1596'), '0501580260',
         (select id from public.networks where code = 'telecel'),
         102400, 30276.41, 'active',
         '2026-07-21T16:48:26.639Z', '2026-09-19T16:48:26.639Z', '2026-07-22T08:20:00.341Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260801-8223'), '0595948207',
         (select id from public.networks where code = 'mtn'),
         2048, 1577.36, 'active',
         '2026-08-01T11:01:15.888Z', NULL, '2026-08-01T17:18:21.309Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260714-5421'), '0590640104',
         (select id from public.networks where code = 'mtn'),
         30720, 15052.22, 'active',
         '2026-07-14T23:01:35.831Z', NULL, '2026-07-15T07:57:22.112Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260809-6077'), '0279039208',
         (select id from public.networks where code = 'airteltigo'),
         30720, 28338.90, 'active',
         '2026-08-09T10:08:20.620Z', '2026-10-08T10:08:20.620Z', '2026-08-09T16:23:22.377Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-2611'), '0247788990',
         (select id from public.networks where code = 'mtn'),
         10240, 821.36, 'active',
         '2026-08-08T03:53:38.700Z', NULL, '2026-08-08T20:31:03.767Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260807-5667'), '0550640824',
         (select id from public.networks where code = 'mtn'),
         3072, 1405.14, 'active',
         '2026-08-07T16:55:08.897Z', NULL, '2026-08-08T00:10:21.322Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-9029'), '0547000432',
         (select id from public.networks where code = 'mtn'),
         102400, 49563.89, 'active',
         '2026-07-19T01:35:13.375Z', NULL, '2026-07-19T22:25:11.085Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260802-8629'), '0269887748',
         (select id from public.networks where code = 'mtn'),
         1024, 818.63, 'active',
         '2026-08-02T13:44:11.692Z', NULL, '2026-08-03T04:35:34.711Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260802-2030'), '0559988776',
         (select id from public.networks where code = 'mtn'),
         3072, 614.35, 'active',
         '2026-08-02T06:22:25.882Z', NULL, '2026-08-03T02:53:56.537Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-2083'), '0551112233',
         (select id from public.networks where code = 'mtn'),
         5120, 4649.36, 'active',
         '2026-08-08T21:31:56.229Z', NULL, '2026-08-09T09:21:08.730Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260727-2835'), '0596109346',
         (select id from public.networks where code = 'mtn'),
         1024, 411.92, 'active',
         '2026-07-27T04:13:08.722Z', NULL, '2026-07-28T01:36:11.828Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260731-2157'), '0561122334',
         (select id from public.networks where code = 'airteltigo'),
         10240, 2773.17, 'active',
         '2026-07-31T09:05:40.778Z', '2026-09-29T09:05:40.778Z', '2026-07-31T19:33:08.491Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260715-8214'), '0272292320',
         (select id from public.networks where code = 'airteltigo'),
         10240, 8724.81, 'active',
         '2026-07-15T04:37:40.465Z', '2026-09-13T04:37:40.465Z', '2026-07-16T00:45:13.779Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-5760'), '0559988776',
         (select id from public.networks where code = 'telecel'),
         10240, 5242.26, 'active',
         '2026-07-19T18:15:14.619Z', '2026-09-17T18:15:14.619Z', '2026-07-20T11:07:41.199Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260715-3458'), '0275346242',
         (select id from public.networks where code = 'airteltigo'),
         30720, 13032.86, 'active',
         '2026-07-15T23:30:06.268Z', '2026-09-13T23:30:06.268Z', '2026-07-16T17:00:45.589Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260804-5883'), '0247788990',
         (select id from public.networks where code = 'mtn'),
         3072, 1846.98, 'active',
         '2026-08-04T09:44:14.297Z', NULL, '2026-08-05T01:05:21.081Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260726-9728'), '0276655443',
         (select id from public.networks where code = 'mtn'),
         1024, 993.28, 'active',
         '2026-07-26T20:34:51.168Z', NULL, '2026-08-11T15:15:49.270Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260717-8085'), '0559988776',
         (select id from public.networks where code = 'telecel'),
         102400, 75290.59, 'active',
         '2026-07-17T03:27:18.286Z', '2026-09-15T03:27:18.286Z', '2026-07-17T09:54:18.365Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260730-6398'), '0263217842',
         (select id from public.networks where code = 'mtn'),
         10240, 2134.66, 'active',
         '2026-07-30T21:47:11.994Z', NULL, '2026-07-31T02:13:01.865Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260807-3982'), '0542245723',
         (select id from public.networks where code = 'mtn'),
         2048, 388.91, 'active',
         '2026-08-07T13:21:07.904Z', NULL, '2026-08-07T22:10:31.610Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260728-6616'), '0502345678',
         (select id from public.networks where code = 'mtn'),
         102400, 51739.42, 'active',
         '2026-07-28T06:43:59.280Z', NULL, '2026-07-28T23:20:56.045Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-6082'), '0561122334',
         (select id from public.networks where code = 'mtn'),
         2048, 1132.46, 'active',
         '2026-07-19T01:52:21.544Z', NULL, '2026-07-19T04:05:34.196Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260803-9502'), '0548612388',
         (select id from public.networks where code = 'mtn'),
         1024, 311.29, 'active',
         '2026-08-03T08:07:09.926Z', NULL, '2026-08-03T10:24:34.270Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260801-8856'), '0247788990',
         (select id from public.networks where code = 'mtn'),
         3072, 1011.74, 'active',
         '2026-08-01T21:23:06.608Z', NULL, '2026-08-01T23:45:33.276Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260731-1914'), '0201122334',
         (select id from public.networks where code = 'mtn'),
         2048, 1761.28, 'active',
         '2026-07-31T21:04:39.302Z', NULL, '2026-08-11T14:21:49.270Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260727-1989'), '0265373760',
         (select id from public.networks where code = 'mtn'),
         5120, 2279.03, 'active',
         '2026-07-27T18:12:31.721Z', NULL, '2026-07-27T20:28:02.861Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260717-9129'), '0273344556',
         (select id from public.networks where code = 'mtn'),
         5120, 1921.21, 'active',
         '2026-07-17T11:59:36.653Z', NULL, '2026-07-17T15:00:36.531Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-2399'), '0559988776',
         (select id from public.networks where code = 'mtn'),
         1024, 318.58, 'active',
         '2026-08-08T12:12:25.465Z', NULL, '2026-08-09T06:43:07.642Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260718-6521'), '0257679524',
         (select id from public.networks where code = 'mtn'),
         30720, 19289.23, 'active',
         '2026-07-18T05:39:10.782Z', NULL, '2026-07-19T02:24:30.365Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-5186'), '0241234567',
         (select id from public.networks where code = 'telecel'),
         10240, 5047.22, 'active',
         '2026-07-19T16:51:43.265Z', '2026-09-17T16:51:43.265Z', '2026-07-19T19:05:22.621Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260806-1699'), '0558491498',
         (select id from public.networks where code = 'mtn'),
         20480, 7715.44, 'active',
         '2026-08-06T08:33:16.166Z', NULL, '2026-08-06T17:35:53.960Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260724-6374'), '0242248702',
         (select id from public.networks where code = 'mtn'),
         30720, 27550.17, 'active',
         '2026-07-24T03:30:51.384Z', NULL, '2026-07-24T06:37:58.942Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260714-3308'), '0551356793',
         (select id from public.networks where code = 'mtn'),
         30720, 16432.64, 'active',
         '2026-07-14T16:15:18.512Z', NULL, '2026-07-15T04:41:35.074Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260719-3132'), '0554076653',
         (select id from public.networks where code = 'mtn'),
         20480, 16353.39, 'active',
         '2026-07-19T22:23:12.166Z', NULL, '2026-07-20T02:27:47.980Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260728-6690'), '0241234567',
         (select id from public.networks where code = 'telecel'),
         102400, 99328.00, 'active',
         '2026-07-28T13:59:49.562Z', '2026-09-26T13:59:49.562Z', '2026-08-11T14:29:49.270Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260804-1913'), '0549948209',
         (select id from public.networks where code = 'mtn'),
         30720, 7408.96, 'active',
         '2026-08-04T17:39:08.292Z', NULL, '2026-08-05T00:57:11.232Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260808-1264'), '0209876543',
         (select id from public.networks where code = 'airteltigo'),
         10240, 4631.06, 'active',
         '2026-08-08T09:17:40.118Z', '2026-10-07T09:17:40.118Z', '2026-08-08T20:39:57.964Z';
  insert into public.bundle_usage (order_id, phone, network_id, size_mb, used_mb, status, started_at, expires_at, last_report_at)
  select (select id from public.orders where reference = 'VD-260717-2866'), '0209876543',
         (select id from public.networks where code = 'telecel'),
         102400, 85153.53, 'active',
         '2026-07-17T09:54:32.337Z', '2026-09-15T09:54:32.337Z', '2026-07-18T00:22:33.932Z';

  -- auto-reload opt-ins (explicit customer consent; relation = self|other)
  insert into public.auto_reload (customer_id, phone, relation, network_id, bundle_id, trigger_percent, momo_number, active, reload_count, last_reload_at, last_triggered_at, cooldown_until, created_at, updated_at)
  select (select id from public.customers where phone = '0241234567'), '0241234567', 'self',
         (select id from public.networks where code = 'mtn'),
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'mtn' and b.size_mb = 1024),
         10, '0245678901', true, 3,
         '2026-08-09T16:23:49.270Z', NULL,
         '2026-08-11T13:43:49.270Z', '2026-07-28T16:45:49.270Z', '2026-07-28T16:45:49.270Z';
  insert into public.auto_reload (customer_id, phone, relation, network_id, bundle_id, trigger_percent, momo_number, active, reload_count, last_reload_at, last_triggered_at, cooldown_until, created_at, updated_at)
  select (select id from public.customers where phone = '0209876543'), '0201122334', 'other',
         (select id from public.networks where code = 'telecel'),
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'telecel' and b.size_mb = 10240),
         20, '0505566778', true, 1,
         '2026-08-05T16:13:49.270Z', NULL,
         '2026-08-11T21:43:49.270Z', '2026-07-31T17:31:49.270Z', '2026-07-31T17:31:49.270Z';
  insert into public.auto_reload (customer_id, phone, relation, network_id, bundle_id, trigger_percent, momo_number, active, reload_count, last_reload_at, last_triggered_at, cooldown_until, created_at, updated_at)
  select (select id from public.customers where phone = '0502345678'), '0276655443', 'other',
         (select id from public.networks where code = 'airteltigo'),
         (select b.id from public.bundles b join public.networks n on n.id = b.network_id where n.code = 'airteltigo' and b.size_mb = 1024),
         15, '0501234321', false, 2,
         '2026-08-02T17:43:49.270Z', NULL,
         NULL, '2026-08-03T15:59:49.270Z', '2026-08-03T15:59:49.270Z';

  -- float ledger (chronological; balance_after chained per network)
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'topup', 3000.00, 3000.00,
         NULL,
         'Initial float (demo seed)', '2026-07-10T16:18:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'topup', 2000.00, 2000.00,
         NULL,
         'Initial float (demo seed)', '2026-07-10T18:25:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'topup', 1500.00, 1500.00,
         NULL,
         'Initial float (demo seed)', '2026-07-10T20:17:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 111.00, 2889.00,
         (select id from public.orders where reference = 'VD-260714-3308'),
         'Delivery cost', '2026-07-14T16:12:37.805Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 111.00, 2778.00,
         (select id from public.orders where reference = 'VD-260714-5421'),
         'Delivery cost', '2026-07-14T23:00:20.593Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 35.50, 1464.50,
         (select id from public.orders where reference = 'VD-260715-8214'),
         'Delivery cost', '2026-07-15T04:37:32.281Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 106.00, 1358.50,
         (select id from public.orders where reference = 'VD-260715-3458'),
         'Delivery cost', '2026-07-15T23:28:52.214Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 1633.00,
         (select id from public.orders where reference = 'VD-260717-8085'),
         'Delivery cost', '2026-07-17T03:25:57.889Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 1266.00,
         (select id from public.orders where reference = 'VD-260717-2866'),
         'Delivery cost', '2026-07-17T09:51:52.483Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 18.90, 2759.10,
         (select id from public.orders where reference = 'VD-260717-9129'),
         'Delivery cost', '2026-07-17T11:57:56.067Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 111.00, 2648.10,
         (select id from public.orders where reference = 'VD-260718-6521'),
         'Delivery cost', '2026-07-18T05:37:24.053Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 377.00, 2271.10,
         (select id from public.orders where reference = 'VD-260719-9029'),
         'Delivery cost', '2026-07-19T01:33:04.576Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 2263.00,
         (select id from public.orders where reference = 'VD-260719-6082'),
         'Delivery cost', '2026-07-19T01:52:34.562Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 2259.10,
         (select id from public.orders where reference = 'VD-260719-4884'),
         'Delivery cost', '2026-07-19T16:12:28.335Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 35.50, 1230.50,
         (select id from public.orders where reference = 'VD-260719-5186'),
         'Delivery cost', '2026-07-19T16:51:24.617Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 35.50, 1195.00,
         (select id from public.orders where reference = 'VD-260719-5760'),
         'Delivery cost', '2026-07-19T18:13:36.592Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 73.00, 2186.10,
         (select id from public.orders where reference = 'VD-260719-3132'),
         'Delivery cost', '2026-07-19T22:21:26.008Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 38.50, 2147.60,
         (select id from public.orders where reference = 'VD-260720-3007'),
         'Delivery cost', '2026-07-20T19:27:53.826Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 35.50, 1159.50,
         (select id from public.orders where reference = 'VD-260721-9488'),
         'Delivery cost', '2026-07-21T06:18:47.727Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 792.50,
         (select id from public.orders where reference = 'VD-260721-1596'),
         'Delivery cost', '2026-07-21T16:45:28.011Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'topup', 1000.00, 3147.60,
         NULL,
         'Restock — MTN float', '2026-07-21T18:41:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 111.00, 3036.60,
         (select id from public.orders where reference = 'VD-260724-6374'),
         'Delivery cost', '2026-07-24T03:30:05.597Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 3032.70,
         (select id from public.orders where reference = 'VD-260726-9728'),
         'Delivery cost', '2026-07-26T20:35:02.239Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 3028.80,
         (select id from public.orders where reference = 'VD-260727-2835'),
         'Delivery cost', '2026-07-27T04:13:33.731Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 18.90, 3009.90,
         (select id from public.orders where reference = 'VD-260727-1989'),
         'Delivery cost', '2026-07-27T18:12:17.763Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 377.00, 2632.90,
         (select id from public.orders where reference = 'VD-260728-6616'),
         'Delivery cost', '2026-07-28T06:43:01.096Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 367.00, 425.50,
         (select id from public.orders where reference = 'VD-260728-6690'),
         'Delivery cost', '2026-07-28T13:59:06.221Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'topup', 800.00, 1225.50,
         NULL,
         'Restock — Telecel float', '2026-07-28T16:05:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'telecel'), 'debit', 98.70, 1126.80,
         (select id from public.orders where reference = 'VD-260729-7594'),
         'Delivery cost', '2026-07-29T05:06:47.385Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 38.50, 2594.40,
         (select id from public.orders where reference = 'VD-260730-6398'),
         'Delivery cost', '2026-07-30T21:44:47.057Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 35.50, 1323.00,
         (select id from public.orders where reference = 'VD-260731-2157'),
         'Delivery cost', '2026-07-31T09:04:15.419Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 2586.30,
         (select id from public.orders where reference = 'VD-260731-1914'),
         'Delivery cost', '2026-07-31T21:02:52.769Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 2578.20,
         (select id from public.orders where reference = 'VD-260801-8223'),
         'Delivery cost', '2026-08-01T11:00:54.566Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 11.90, 2566.30,
         (select id from public.orders where reference = 'VD-260801-8856'),
         'Delivery cost', '2026-08-01T21:21:16.284Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 11.90, 2554.40,
         (select id from public.orders where reference = 'VD-260802-2030'),
         'Delivery cost', '2026-08-02T06:22:54.162Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 2550.50,
         (select id from public.orders where reference = 'VD-260802-8629'),
         'Delivery cost', '2026-08-02T13:42:19.352Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'topup', 600.00, 1923.00,
         NULL,
         'Restock — AirtelTigo float', '2026-08-02T20:31:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 2546.60,
         (select id from public.orders where reference = 'VD-260803-9502'),
         'Delivery cost', '2026-08-03T08:07:22.553Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 11.90, 2534.70,
         (select id from public.orders where reference = 'VD-260804-5883'),
         'Delivery cost', '2026-08-04T09:41:57.045Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 111.00, 2423.70,
         (select id from public.orders where reference = 'VD-260804-1913'),
         'Delivery cost', '2026-08-04T17:38:49.460Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 2415.60,
         (select id from public.orders where reference = 'VD-260806-6799'),
         'Delivery cost', '2026-08-06T08:11:40.926Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 73.00, 2342.60,
         (select id from public.orders where reference = 'VD-260806-1699'),
         'Delivery cost', '2026-08-06T08:31:46.045Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 377.00, 1965.60,
         (select id from public.orders where reference = 'VD-260806-8219'),
         'Delivery cost', '2026-08-06T22:28:31.674Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 8.10, 1957.50,
         (select id from public.orders where reference = 'VD-260807-3982'),
         'Delivery cost', '2026-08-07T13:21:46.768Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 11.90, 1945.60,
         (select id from public.orders where reference = 'VD-260807-5667'),
         'Delivery cost', '2026-08-07T16:53:14.662Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'topup', 500.00, 2445.60,
         NULL,
         'Restock — MTN float', '2026-08-07T17:27:49.270Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 38.50, 2407.10,
         (select id from public.orders where reference = 'VD-260808-2611'),
         'Delivery cost', '2026-08-08T03:51:23.709Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 35.50, 1887.50,
         (select id from public.orders where reference = 'VD-260808-1264'),
         'Delivery cost', '2026-08-08T09:18:30.498Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 3.90, 2403.20,
         (select id from public.orders where reference = 'VD-260808-2399'),
         'Delivery cost', '2026-08-08T12:11:45.108Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'mtn'), 'debit', 18.90, 2384.30,
         (select id from public.orders where reference = 'VD-260808-2083'),
         'Delivery cost', '2026-08-08T21:30:43.240Z';
  insert into public.float_ledger (network_id, direction, amount, balance_after, order_id, note, created_at)
  select (select id from public.networks where code = 'airteltigo'), 'debit', 106.00, 1781.50,
         (select id from public.orders where reference = 'VD-260809-6077'),
         'Delivery cost', '2026-08-09T10:07:46.824Z';

  -- audit log (forged callbacks & unknown-order entries included on purpose)
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260714-4366","reference":"VD-260714-3308","amount":125,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-14T16:14:23.406Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260714-RM7J","reference":"VD-260714-5421","amount":125,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-14T23:04:08.034Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260715-DENA","reference":"VD-260715-8214","amount":39,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-15T04:41:01.743Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260715-F3VS","reference":"VD-260715-7057","amount":9,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-15T12:01:43.683Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260715-Q73K","reference":"VD-260715-3458","amount":117,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-15T23:28:54.393Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260716-QXUG","reference":"VD-260716-9122","amount":125,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-16T09:48:59.003Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260717-6G94","reference":"VD-260717-8085","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-17T03:28:41.623Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260717-TXLG","reference":"VD-260717-2866","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-17T09:55:19.980Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260717-LKLL","reference":"VD-260717-9129","amount":20.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-17T12:00:40.252Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260718-8CDL","reference":"VD-260718-6521","amount":125,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-18T05:41:14.338Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-SYQ7","reference":"VD-260719-9029","amount":407,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T01:36:34.595Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-SEFJ","reference":"VD-260719-6082","amount":9,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T01:52:43.923Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-YWN8","reference":"VD-260719-4884","amount":4.2,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T16:12:52.539Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-4G2T","reference":"VD-260719-5186","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T16:53:58.687Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-AY27","reference":"VD-260719-5760","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T18:15:32.212Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260719-B4K6","reference":"VD-260719-3132","amount":82,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-19T22:22:01.119Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260720-2H3S","reference":"VD-260720-3007","amount":43,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-20T19:29:49.816Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260721-YCXQ","reference":"VD-260721-9488","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-21T06:21:36.116Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260721-GJYS","reference":"VD-260721-1596","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-21T16:47:00.528Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260724-EFMV","reference":"VD-260724-6374","amount":125,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-24T03:30:36.036Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260726-S3Y9","reference":"VD-260726-9728","amount":4.2,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-26T20:38:23.819Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260727-8KUQ","reference":"VD-260727-2835","amount":4.2,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-27T04:15:41.771Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260727-L7JC","reference":"VD-260727-1989","amount":20.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-27T18:12:29.859Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260728-PY9V","reference":"VD-260728-6616","amount":407,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-28T06:45:22.705Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260728-Y4CF","reference":"VD-260728-6690","amount":405,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-28T14:01:06.125Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260728-TTFX","reference":"VD-260728-3783","amount":19.9,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-28T15:03:55.488Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260729-32J9","reference":"VD-260729-7594","amount":110,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-29T05:09:21.406Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260730-HU34","reference":"VD-260730-6398","amount":43,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-30T21:48:44.936Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260731-CLVP","reference":"VD-260731-2157","amount":39,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-31T09:07:33.762Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260731-XC9N","reference":"VD-260731-1914","amount":9,"currency":"GHS"}'::jsonb, true, NULL, '2026-07-31T21:03:21.447Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260801-WK5G","reference":"VD-260801-8223","amount":9,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-01T11:03:45.415Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260801-B6RB","reference":"VD-260801-8856","amount":13.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-01T21:24:38.245Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260802-4VR3","reference":"VD-260802-2030","amount":13.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-02T06:26:19.500Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260802-V3VV","reference":"VD-260802-8629","amount":4.2,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-02T13:45:22.911Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260803-R8FU","reference":"VD-260803-9502","amount":4.2,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-03T08:10:04.312Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.failed","provider_reference":"VP-260803-FFFF","reference":"VD-260803-0000","amount":39.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-03T19:28:49.270Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260804-QXY3","reference":"VD-260804-5883","amount":13.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-04T09:43:17.724Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260804-CT8W","reference":"VD-260804-2384","amount":82,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-04T17:23:31.688Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260804-JBZS","reference":"VD-260804-1913","amount":125,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-04T17:40:52.568Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260805-ZZZZ","reference":"VD-260805-0000","amount":19.9,"currency":"GHS"}'::jsonb, true, 'unknown order VD-260805-0000', '2026-08-05T19:19:49.270Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260806-MDFU","reference":"VD-260806-6799","amount":9,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-06T08:14:27.086Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260806-9M5L","reference":"VD-260806-1699","amount":82,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-06T08:34:49.059Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260806-TBQH","reference":"VD-260806-8219","amount":407,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-06T22:29:44.022Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260807-JH2W","reference":"VD-260807-3982","amount":9,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-07T13:23:50.857Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260807-H7LM","reference":"VD-260807-5667","amount":13.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-07T16:54:20.058Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-UQS2","reference":"VD-260808-2611","amount":43,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T03:52:44.020Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-VW9C","reference":"VD-260808-1264","amount":39,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T09:21:03.078Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-FBE4","reference":"VD-260808-2399","amount":4.2,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T12:12:25.101Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (false, '{"event":"payment.succeeded","provider_reference":"VP-TEST-FORGED1","reference":"VD-260808-0000","amount":43,"currency":"GHS"}'::jsonb, true, 'invalid signature', '2026-08-08T16:20:49.270Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-AH6A","reference":"VD-260808-5150","amount":117,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T17:07:19.041Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260808-J63L","reference":"VD-260808-2083","amount":20.5,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-08T21:33:09.040Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260809-N9VC","reference":"VD-260809-4475","amount":405,"currency":"GHS"}'::jsonb, true, 'amount mismatch → refunded', '2026-08-09T04:28:20.959Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (true, '{"event":"payment.succeeded","provider_reference":"VP-260809-MVK5","reference":"VD-260809-6077","amount":117,"currency":"GHS"}'::jsonb, true, NULL, '2026-08-09T10:11:40.363Z');
  insert into public.webhook_log (signature_valid, payload, handled, error, created_at)
  values (false, '{"event":"payment.succeeded","provider_reference":"VP-TEST-FORGED2","reference":"VD-260809-0000","amount":9,"currency":"GHS"}'::jsonb, true, 'invalid signature', '2026-08-09T17:29:49.270Z');

  raise notice 'Valmont Data demo seed complete: % customers, % saved numbers, % orders, % usage rows, % auto-reload rules, % float entries, % webhook logs (final float: MTN %, Telecel %, AirtelTigo %).',
    5, 16, 52, 44, 3, 51, 54,
    2384.30, 1126.80, 1781.50;
end $$;
