/* Deterministic demo catalogue so the marketplace is never empty on first run. */

import crypto from "node:crypto";
import type { Ad, AdCondition } from "./types";
import { slugify } from "./store";

interface Row {
  title: string;
  category: string;
  subcategory: string;
  price: number | null;
  condition: AdCondition;
  region: string;
  town: string;
  description: string;
  sellerName: string;
  sellerPhone: string;
  sellerType?: "private" | "business";
  featured?: boolean;
  status?: Ad["status"];
  views?: number;
  ageHours?: number;
  images?: string[];
  /** Demo paid promotion — sold as a Valmont Web package add-on. */
  promo?: { clientName: string; websiteUrl: string; packageRef: string; tier: "spotlight" | "boost"; clicks: number; impressions: number };
}

const ROWS: Row[] = [
  {
    title: "iPhone 14 Pro Max 256GB — Deep Purple",
    category: "phones-tablets",
    subcategory: "Mobile Phones",
    price: 8200,
    condition: "used-excellent",
    region: "Greater Accra",
    town: "East Legon",
    description:
      "iPhone 14 Pro Max, 256GB, Deep Purple. Battery health 91%, no scratches, always used with a case and screen protector. Comes with original box, cable and a free tempered glass. Face ID perfect, no iCloud lock. Meet at East Legon or Accra Mall — inspection welcome before payment.",
    sellerName: "Kwame Boateng",
    sellerPhone: "0244118822",
    featured: true,
    views: 1284,
    ageHours: 6,
    images: ["/uploads/iphone-14-pro-max.jpg"],
  },
  {
    title: "Toyota Corolla 2018 — Registered, Low Mileage",
    category: "vehicles",
    subcategory: "Cars",
    price: 148000,
    condition: "used-excellent",
    region: "Greater Accra",
    town: "Spintex",
    description:
      "Toyota Corolla LE 2018, duty fully paid and registered in Ghana. 78,000 km on the clock, accident-free, engine and gearbox in perfect condition. Fresh service done last month (oil, filters, brake pads). AC very cold, reverse camera, alloy rims. Serious buyers only — test drive available at Spintex.",
    sellerName: "Adjei Motors",
    sellerPhone: "0201445566",
    sellerType: "business",
    featured: true,
    views: 2140,
    ageHours: 20,
    images: ["/uploads/toyota-corolla.jpg"],
  },
  {
    title: "2 Bedroom Apartment for Rent — East Legon Hills",
    category: "property",
    subcategory: "Apartments for Rent",
    price: 3200,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "East Legon",
    description:
      "Newly built 2 bedroom apartment at East Legon Hills. Tiled floors, fitted kitchen with cabinets, en-suite master bedroom, hot water, wardrobe in each room. Gated compound with 24/7 security, borehole plus GWCL, and parking for two cars. Price is per month, one year advance. Agent fee applies.",
    sellerName: "Nana Ama Realty",
    sellerPhone: "0554332211",
    sellerType: "business",
    featured: true,
    views: 1890,
    ageHours: 30,
    images: ["/uploads/apartment-east-legon.jpg"],
  },
  {
    title: "MacBook Air M2 13-inch 8GB/256GB",
    category: "electronics",
    subcategory: "Laptops",
    price: 9500,
    condition: "used-excellent",
    region: "Ashanti",
    town: "Kumasi",
    description:
      "MacBook Air M2, 8GB RAM, 256GB SSD, Midnight. 42 charge cycles only, bought from the US last year. Keyboard and screen flawless, no dents. Includes original 35W charger and a sleeve. Ideal for students and designers. Located at Adum, Kumasi — can ship via VIP or STC to any region after payment confirmation.",
    sellerName: "Yaw Mensah",
    sellerPhone: "0245667788",
    views: 940,
    ageHours: 44,
    images: ["/uploads/macbook-air.jpg"],
  },
  {
    title: "Samsung Galaxy A55 5G 128GB — Brand New Sealed",
    category: "phones-tablets",
    subcategory: "Mobile Phones",
    price: 4150,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Osu",
    description:
      "Brand new sealed Samsung Galaxy A55 5G, 8GB RAM / 128GB storage. Official Ghana warranty one year. Colours available: Awesome Navy, Iceblue, Lilac. Walk into our Osu shop or we deliver same day within Accra for GH₵30. Bulk pricing available for resellers.",
    sellerName: "Osu Phone Hub",
    sellerPhone: "0277889900",
    sellerType: "business",
    views: 612,
    ageHours: 9,
  },
  {
    title: "Honda CB125F Motorbike — 2021",
    category: "vehicles",
    subcategory: "Motorbikes",
    price: 12500,
    condition: "used-good",
    region: "Northern",
    town: "Tamale",
    description:
      "Honda CB125F 2021 model in good running condition. Regularly serviced, new tyres fitted two months ago, chain and sprocket recently replaced. Documents complete — insurance valid till December. Perfect for delivery riders. Small negotiation allowed for a serious buyer in Tamale.",
    sellerName: "Abdul Rahman",
    sellerPhone: "0208112233",
    views: 430,
    ageHours: 52,
  },
  {
    title: "Executive Office Desk & Leather Chair Set",
    category: "home-furniture",
    subcategory: "Furniture",
    price: 2800,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Tema",
    description:
      "Brand new executive office desk (1.6m) with side drawer unit plus a high-back leather swivel chair. Solid MDF with scratch-resistant finish. Delivery and assembly free within Tema and Accra. We also stock conference tables, workstations and reception counters — visit our Tema Community 1 showroom.",
    sellerName: "Tema Furniture Works",
    sellerPhone: "0302554433".replace("0302", "0242"),
    sellerType: "business",
    views: 288,
    ageHours: 70,
  },
  {
    title: "Sony PlayStation 5 Slim + 2 Pads + FIFA 25",
    category: "electronics",
    subcategory: "Gaming",
    price: 6900,
    condition: "used-excellent",
    region: "Greater Accra",
    town: "Dansoman",
    description:
      "PS5 Slim disc edition, barely used, bought in March. Comes with two DualSense controllers, FIFA 25 disc, Spider-Man 2 digital, all cables and the original box. No faults at all, console still smells new. Selling because I am relocating. Inspection at Dansoman, no swap.",
    sellerName: "Selorm K.",
    sellerPhone: "0559004411",
    views: 1520,
    ageHours: 15,
    images: ["/uploads/ps5-slim.jpg"],
  },
  {
    title: "Experienced Sales Associate — Retail Shop (Accra)",
    category: "jobs",
    subcategory: "Full Time",
    price: 1800,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Accra Central",
    description:
      "We are hiring a sales associate for a phone accessories retail shop at Accra Central. Requirements: SHS/HND, minimum one year retail experience, good English and Twi, honest and punctual. Salary GH₵1,800 monthly plus commission on sales targets. Working hours 8am–6pm, Monday to Saturday. Send your CV via WhatsApp.",
    sellerName: "BrightMart Ghana",
    sellerPhone: "0246778899",
    sellerType: "business",
    views: 3260,
    ageHours: 26,
  },
  {
    title: "AC Installation, Servicing & Gas Refill — All Accra",
    category: "services",
    subcategory: "Repairs",
    price: 250,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Madina",
    description:
      "Professional air conditioner installation, servicing, gas refilling and repairs for split and window units. Six years experience, certified technician, we work on Samsung, LG, Nasco, Midea, TCL and Hisense. Price from GH₵250 depending on the job. Same-day service anywhere in Accra and Tema. Three months workmanship guarantee.",
    sellerName: "CoolTech Services",
    sellerPhone: "0264556677",
    sellerType: "business",
    views: 780,
    ageHours: 34,
  },
  {
    title: "15KVA Perkins Soundproof Generator",
    category: "business-industrial",
    subcategory: "Generators",
    price: 42000,
    condition: "used-good",
    region: "Western",
    town: "Takoradi",
    description:
      "15KVA Perkins soundproof generator with automatic transfer switch. Used in a small hotel, well maintained with service book available. Runs quietly, low fuel consumption, control panel fully functional. Buyer arranges transport from Takoradi. Price slightly negotiable for cash payment.",
    sellerName: "Kojo Enterprise",
    sellerPhone: "0203344556",
    sellerType: "business",
    views: 355,
    ageHours: 96,
  },
  {
    title: "Ladies Ankara Dresses — Wholesale from GH₵85",
    category: "fashion",
    subcategory: "Clothing",
    price: 85,
    condition: "brand-new",
    region: "Ashanti",
    town: "Kumasi",
    description:
      "Quality Ankara dresses sewn by our in-house tailors. Sizes 8 to 20, custom sizes on request. Wholesale price GH₵85 per piece for a minimum of ten pieces, retail GH₵130. New designs every two weeks. Nationwide delivery through bus or dispatch rider. Payment on delivery available in Kumasi only.",
    sellerName: "Akosua Styles",
    sellerPhone: "0248001122",
    sellerType: "business",
    views: 1130,
    ageHours: 12,
    images: ["/uploads/ankara-dresses.jpg"],
    promo: {
      clientName: "Akosua Styles",
      websiteUrl: "https://akosuastyles.com",
      packageRef: "VW-2026-0142",
      tier: "spotlight",
      clicks: 214,
      impressions: 4820,
    },
  },
  {
    title: "Plot of Land at Oyibi — 70x100, Registered Title",
    category: "property",
    subcategory: "Land & Plots",
    price: 95000,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Adenta",
    description:
      "One plot (70x100) at Oyibi, five minutes from the main road and close to Valley View University. Documents: registered indenture, site plan and land title certificate all available for inspection at Lands Commission. Litigation free, family land with all consents signed. Serious buyers can inspect any weekday.",
    sellerName: "Mensah Landholdings",
    sellerPhone: "0209887766",
    sellerType: "business",
    views: 660,
    ageHours: 120,
  },
  {
    title: "Hisense 55-inch 4K Smart TV",
    category: "electronics",
    subcategory: "TVs",
    price: 4300,
    condition: "brand-new",
    region: "Central",
    town: "Cape Coast",
    description:
      "Hisense 55A6K 55-inch 4K UHD smart TV with VIDAA OS, Netflix and YouTube built in. Brand new in box with two-year supplier warranty. Free wall bracket and delivery within Cape Coast. We also have 43-inch and 65-inch in stock. Instalment plan available with 50% deposit.",
    sellerName: "Coastline Electricals",
    sellerPhone: "0273322110",
    sellerType: "business",
    views: 402,
    ageHours: 58,
  },
  {
    title: "Home Cleaning & Fumigation Service",
    category: "services",
    subcategory: "Cleaning",
    price: 400,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Achimota",
    description:
      "Deep cleaning for homes, offices and post-construction sites, plus safe fumigation against roaches, bedbugs, rats and termites. Trained and uniformed staff, own equipment and eco-friendly chemicals. From GH₵400 for a one bedroom. We serve Accra, Tema and Kasoa, seven days a week including public holidays.",
    sellerName: "SparkleHome GH",
    sellerPhone: "0556677889",
    sellerType: "business",
    views: 512,
    ageHours: 40,
  },
  {
    title: "Layer Birds — Point of Lay (Per Bird)",
    category: "agriculture",
    subcategory: "Livestock",
    price: 65,
    condition: "not-applicable",
    region: "Bono",
    town: "Sunyani",
    description:
      "Healthy point of lay layer birds, 16 weeks old, fully vaccinated with records available. Isa Brown breed, good laying performance. GH₵65 per bird, discount for orders above 200 birds. We arrange transport in ventilated crates to any region. Farm visits welcome by appointment near Sunyani.",
    sellerName: "Ahenkro Farms",
    sellerPhone: "0242119933",
    sellerType: "business",
    views: 297,
    ageHours: 66,
  },
  {
    title: "Tecno Spark 20 Pro 256GB — Swap Allowed",
    category: "phones-tablets",
    subcategory: "Mobile Phones",
    price: 1650,
    condition: "used-good",
    region: "Eastern",
    town: "Koforidua",
    description:
      "Tecno Spark 20 Pro, 8GB RAM and 256GB storage, six months old. Screen and body clean with a small scuff on the frame shown in photos. Battery lasts a full day easily. Selling or swapping for an iPhone 11 with your top-up. Meet at Koforidua Central for inspection.",
    sellerName: "Papa Kwesi",
    sellerPhone: "0269911223",
    views: 210,
    ageHours: 8,
  },
  {
    title: "Private Maths & Science Tutor — JHS/SHS",
    category: "services",
    subcategory: "Tutoring",
    price: 600,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Adenta",
    description:
      "Experienced tutor available for Core and Elective Maths, Integrated Science and Physics for JHS and SHS students. BSc graduate with five years of teaching, strong BECE and WASSCE results. Home lessons in Adenta, Madina, East Legon and Ashaley Botwe, or online. GH₵600 monthly for two sessions weekly.",
    sellerName: "Mr. Danso",
    sellerPhone: "0553311447",
    views: 445,
    ageHours: 18,
  },
  {
    title: "Double Door Fridge — Nasco 350L",
    category: "home-furniture",
    subcategory: "Home Appliances",
    price: 3100,
    condition: "used-excellent",
    region: "Volta",
    town: "Ho",
    description:
      "Nasco 350 litre double door fridge, silver finish, three years old but works perfectly and cools very fast. Selling because we upgraded to a bigger side-by-side unit. No dents or rust, seals intact, energy efficient. Pick up from Ho, buyer arranges transport. Small negotiation possible.",
    sellerName: "Elikem A.",
    sellerPhone: "0203998877",
    views: 176,
    ageHours: 78,
  },
  {
    title: "Canon EOS 90D + 18-135mm Lens",
    category: "electronics",
    subcategory: "Cameras",
    price: 11500,
    condition: "used-excellent",
    region: "Greater Accra",
    town: "Spintex",
    description:
      "Canon EOS 90D DSLR with the 18-135mm IS USM kit lens. Shutter count under 15,000, sensor spotless, no fungus in the lens. Bundle includes two batteries, 64GB card, camera bag and a spare charger. Perfect for wedding and content creators starting out. Inspection at Spintex, cash or MoMo.",
    sellerName: "FrameGH Studios",
    sellerPhone: "0245512399",
    sellerType: "business",
    views: 690,
    ageHours: 28,
  },
  {
    title: "Bulk Fresh Tomatoes — Per Crate",
    category: "agriculture",
    subcategory: "Produce",
    price: 480,
    condition: "not-applicable",
    region: "Upper East",
    town: "Navrongo",
    description:
      "Freshly harvested tomatoes sold per crate directly from our Navrongo farm. Firm, well graded and suitable for market traders, restaurants and processors. Price varies with the season, currently GH₵480 per crate. We can load a truck for buyers taking twenty crates or more. Call early to reserve.",
    sellerName: "Atongo Farms",
    sellerPhone: "0207766554",
    sellerType: "business",
    views: 133,
    ageHours: 88,
  },
  {
    title: "Barbering Salon Equipment — Complete Setup",
    category: "business-industrial",
    subcategory: "Restaurant Equipment",
    price: 7400,
    condition: "used-good",
    region: "Ashanti",
    town: "Asokwa",
    description:
      "Complete barbering shop setup for sale: three hydraulic chairs, two large mirrors with cabinets, wash basin, sterilizer, four clippers, waiting bench and a wall TV. Everything in working order, shop closing due to relocation. Buy the lot for GH₵7,400 or make an offer for individual items.",
    sellerName: "Kofi Barbers",
    sellerPhone: "0248877665",
    views: 254,
    ageHours: 104,
  },
  {
    title: "Suzuki Alto 2016 — Very Economical",
    category: "vehicles",
    subcategory: "Cars",
    price: 52000,
    condition: "used-good",
    region: "Greater Accra",
    town: "Kasoa",
    description:
      "Suzuki Alto 2016, home used, very low fuel consumption which makes it perfect for Uber and Bolt. Duty paid, registration valid, roadworthy till next year. Body has minor scratches typical for its age, mechanically sound with no leaks. First to see will buy. Located at Kasoa.",
    sellerName: "Yaa Asantewaa",
    sellerPhone: "0554411778",
    views: 820,
    ageHours: 36,
  },
  {
    title: "Graphic Designer Needed — Remote, Part Time",
    category: "jobs",
    subcategory: "Remote",
    price: 2500,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Accra Central",
    description:
      "Remote part-time graphic designer wanted for a growing Ghanaian brand. You will handle social media creatives, flyers and simple motion graphics. Must know Figma or Adobe suite and have a portfolio. Twenty hours a week, GH₵2,500 monthly, paid via MoMo every month end. Send portfolio link on WhatsApp.",
    sellerName: "Kente Digital",
    sellerPhone: "0501122334",
    sellerType: "business",
    views: 2870,
    ageHours: 22,
  },
  {
    title: "Human Hair Wig — 20 inch Body Wave",
    category: "fashion",
    subcategory: "Hair & Beauty",
    price: 1450,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Osu",
    description:
      "100% human hair body wave wig, 20 inches, 13x4 HD lace frontal with pre-plucked hairline and bleached knots. Density 180%, can be dyed and styled with heat. Free customisation and installation at our Osu studio when you buy. Nationwide delivery available, payment before dispatch outside Accra.",
    sellerName: "Adjoa Hair Bar",
    sellerPhone: "0559988771",
    sellerType: "business",
    views: 985,
    ageHours: 10,
  },
  {
    title: "Shop Space for Rent at Circle — Ground Floor",
    category: "property",
    subcategory: "Commercial",
    price: 2500,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Accra Central",
    description:
      "Ground floor shop space of about 20 square metres at Kwame Nkrumah Circle, facing the main walkway with very high foot traffic. Suitable for phones, cosmetics, boutique or a pharmacy. Rent GH₵2,500 monthly, two years advance required. Prepaid meter installed, washroom shared in the building.",
    sellerName: "Circle Property Agents",
    sellerPhone: "0276655443",
    sellerType: "business",
    views: 540,
    ageHours: 130,
  },
  {
    title: "Free-standing Gas Cooker with Oven — 4 Burner",
    category: "home-furniture",
    subcategory: "Kitchen",
    price: 2650,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Spintex",
    description:
      "Brand new four burner gas cooker with oven and grill, stainless steel top with auto ignition and flame failure safety. One year warranty from the supplier. Free delivery within Spintex, Tema and East Legon. We also stock chest freezers, blenders and microwaves at wholesale prices.",
    sellerName: "HomeEssentials GH",
    sellerPhone: "0244667711",
    sellerType: "business",
    views: 320,
    ageHours: 50,
  },
  {
    title: "Dispatch Rider Available for Hire — Daily/Monthly",
    category: "services",
    subcategory: "Transport",
    price: 1500,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Achimota",
    description:
      "Experienced dispatch rider with own bike available for businesses needing daily deliveries around Accra. Knows the city very well, punctual, polite and careful with fragile items. GH₵1,500 monthly retainer for a fixed daily route, or GH₵80 per drop for one-off jobs. References available on request.",
    sellerName: "Ibrahim Musah",
    sellerPhone: "0246633998",
    views: 361,
    ageHours: 14,
  },
  {
    title: "iPad 10th Gen 64GB WiFi — Silver",
    category: "phones-tablets",
    subcategory: "Tablets",
    price: 3900,
    condition: "used-excellent",
    region: "Ashanti",
    town: "Kumasi",
    description:
      "iPad 10th generation, 64GB WiFi model in silver. Used for about eight months for lecture notes, battery still excellent and the screen has no scratches thanks to a screen protector from day one. Includes charger, case and a stylus. No iCloud lock, ready to set up as new.",
    sellerName: "Nana Kwabena",
    sellerPhone: "0208899221",
    views: 288,
    ageHours: 16,
  },
  {
    title: "Wedding Decoration & Event Planning",
    category: "services",
    subcategory: "Events",
    price: 6000,
    condition: "not-applicable",
    region: "Central",
    town: "Winneba",
    description:
      "Full wedding and engagement decoration: backdrop, chair covers, centrepieces, aisle setup, lighting and draping. Packages from GH₵6,000 depending on guest count and venue. We cover Central, Greater Accra and Western regions. Book at least three weeks ahead. Photos of past events available on WhatsApp.",
    sellerName: "Grace Events",
    sellerPhone: "0559911002",
    sellerType: "business",
    views: 470,
    ageHours: 60,
  },
  {
    title: "Office Laptop Bundle — 5x Dell Latitude 7490",
    category: "electronics",
    subcategory: "Laptops",
    price: 15500,
    condition: "used-good",
    region: "Greater Accra",
    town: "Tema",
    description:
      "Five Dell Latitude 7490 laptops sold as a bundle: Core i5 8th gen, 8GB RAM, 256GB SSD each. Ex-UK stock, all tested and working with fresh Windows 11 installs. Ideal for a small office, school lab or internet cafe. GH₵15,500 for all five, or GH₵3,300 each if you want fewer.",
    sellerName: "TechSurplus Ghana",
    sellerPhone: "0272211447",
    sellerType: "business",
    views: 388,
    ageHours: 72,
  },
  {
    title: "Men's Leather Shoes — Italian Style, All Sizes",
    category: "fashion",
    subcategory: "Shoes",
    price: 320,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Madina",
    description:
      "Quality men's leather shoes in Oxford, Derby and loafer styles. Sizes 39 to 46 available in black and brown. GH₵320 per pair retail, GH₵260 for five pairs and above. Real leather upper with a comfortable rubber sole. Delivery nationwide, pay on delivery within Accra.",
    sellerName: "Madina Shoe Plaza",
    sellerPhone: "0203377991",
    sellerType: "business",
    views: 265,
    ageHours: 46,
  },
  {
    title: "Sound System Rental — Speakers, Mixer, Mics",
    category: "services",
    subcategory: "Events",
    price: 1200,
    condition: "not-applicable",
    region: "Ashanti",
    town: "Kumasi",
    description:
      "Professional sound system for rent: two 15-inch active speakers, subwoofer, twelve channel mixer, four wireless microphones and stands. Suitable for church programmes, funerals, weddings and outdoor events up to 400 people. GH₵1,200 per day including setup and an operator. Kumasi and nearby towns.",
    sellerName: "SoundLink Kumasi",
    sellerPhone: "0246611884",
    sellerType: "business",
    views: 198,
    ageHours: 92,
  },
  {
    title: "Brand New Mattress — 6x6 Orthopaedic",
    category: "home-furniture",
    subcategory: "Furniture",
    price: 1900,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Kasoa",
    description:
      "Six by six orthopaedic mattress, ten inches thick with a firm support core and quilted cover. Brand new and sealed, five year warranty from the manufacturer. Free delivery to Kasoa, Weija and Mallam. Other sizes available including 4x6 and 5x6. Discount when you buy two or more.",
    sellerName: "Sleepwell GH",
    sellerPhone: "0554400229",
    sellerType: "business",
    views: 231,
    ageHours: 54,
  },
  {
    title: "Driver Wanted — Personal Driver, Airport Area",
    category: "jobs",
    subcategory: "Full Time",
    price: 2200,
    condition: "not-applicable",
    region: "Greater Accra",
    town: "Accra Central",
    description:
      "Looking for an experienced personal driver for a family residing near the Airport Residential Area. Must have a valid licence for at least five years, clean record, know Accra roads well and be presentable. Monday to Saturday, GH₵2,200 monthly plus lunch allowance. Guarantor required at interview.",
    sellerName: "Private Household",
    sellerPhone: "0244990033",
    views: 4120,
    ageHours: 42,
  },
  {
    title: "Xiaomi Redmi Note 13 — 8GB/256GB",
    category: "phones-tablets",
    subcategory: "Mobile Phones",
    price: 2350,
    condition: "brand-new",
    region: "Western",
    town: "Takoradi",
    description:
      "Xiaomi Redmi Note 13, 8GB RAM and 256GB storage, brand new and sealed with a one year warranty. 108MP camera, 5000mAh battery and 33W fast charging in the box. Available in Midnight Black and Ice Blue. Takoradi Market Circle shop, delivery to Sekondi and Tarkwa available.",
    sellerName: "Harbour Gadgets",
    sellerPhone: "0273388776",
    sellerType: "business",
    views: 344,
    ageHours: 24,
  },
  {
    title: "Suspicious deal — advance fee required upfront",
    category: "electronics",
    subcategory: "Laptops",
    price: 400,
    condition: "brand-new",
    region: "Greater Accra",
    town: "Accra Central",
    description:
      "Cheap laptops available but you must send an advance fee before we ship. Payment by western union only. This listing exists to demonstrate the automated screening — it is auto-rejected on submission.",
    sellerName: "Unverified Poster",
    sellerPhone: "0201010101",
    status: "rejected",
    views: 3,
    ageHours: 5,
  },
  {
    title: "Chest Freezer 200L — Barely Used",
    category: "home-furniture",
    subcategory: "Home Appliances",
    price: 2400,
    condition: "used-excellent",
    region: "Greater Accra",
    town: "Adenta",
    description:
      "Two hundred litre chest freezer used for only four months in a shop that has now closed. Freezes very well and quickly, interior clean with no odour, wheels and basket intact. Comes with the original receipt and remaining warranty card. Pick up at Adenta, price slightly negotiable.",
    sellerName: "Ama Serwaa",
    sellerPhone: "0559922114",
    status: "pending",
    views: 0,
    ageHours: 2,
  },
  {
    title: "Yamaha Keyboard PSR-E473 with Stand",
    category: "electronics",
    subcategory: "Audio & Speakers",
    price: 5200,
    condition: "used-excellent",
    region: "Greater Accra",
    town: "Dansoman",
    description:
      "Yamaha PSR-E473 61-key keyboard with adjustable stand, sustain pedal and power adapter. All keys and buttons work perfectly, no dead notes. Used mostly at home for practice and a few church services. Great for learners and worship teams. Inspection welcome at Dansoman before payment.",
    sellerName: "Emmanuel O.",
    sellerPhone: "0246622007",
    status: "pending",
    views: 0,
    ageHours: 3,
  },
  {
    title: "Hyundai Grand i10 2019 — Sold",
    category: "vehicles",
    subcategory: "Cars",
    price: 88000,
    condition: "used-good",
    region: "Ashanti",
    town: "Kumasi",
    description:
      "Hyundai Grand i10 2019, duty paid, home used with full service history. This unit has now been sold — kept here so buyers can see typical asking prices for the model in Kumasi. Contact us for similar vehicles arriving in stock every two weeks.",
    sellerName: "Adum Auto Sales",
    sellerPhone: "0208844112",
    sellerType: "business",
    status: "sold",
    views: 1420,
    ageHours: 200,
  },
];

export function seedAds(): Ad[] {
  const now = Date.now();
  const used = new Set<string>();

  return ROWS.map((r, i) => {
    const base = slugify(r.title);
    let slug = base;
    let n = 2;
    while (used.has(slug)) slug = `${base}-${n++}`;
    used.add(slug);

    const created = new Date(now - (r.ageHours ?? 24 + i * 3) * 3600 * 1000);
    const d = created.toISOString().slice(2, 10).replace(/-/g, "");

    return {
      id: crypto.createHash("sha1").update(slug).digest("hex").slice(0, 24),
      ref: `VA-${d}-${1000 + i * 37}`,
      title: r.title,
      slug,
      category: r.category,
      subcategory: r.subcategory,
      price: r.price,
      negotiable: i % 3 === 0,
      condition: r.condition,
      region: r.region,
      town: r.town,
      description: r.description,
      images: r.images ?? [],
      sellerName: r.sellerName,
      sellerPhone: r.sellerPhone,
      whatsapp: i % 5 !== 0,
      sellerType: r.sellerType ?? "private",
      status: r.status ?? "active",
      featured: Boolean(r.featured),
      views: r.views ?? 0,
      leads: Math.floor((r.views ?? 0) / 90),
      createdAt: created.toISOString(),
      updatedAt: created.toISOString(),
      expiresAt: new Date(created.getTime() + 30 * 24 * 3600 * 1000).toISOString(),
      rejectionReason: r.status === "rejected" ? "Flagged phrase: “advance fee”" : undefined,
      promotion: r.promo
        ? {
            tier: r.promo.tier,
            clientName: r.promo.clientName,
            websiteUrl: r.promo.websiteUrl,
            packageRef: r.promo.packageRef,
            startedAt: created.toISOString(),
            expiresAt: new Date(now + 21 * 24 * 3600 * 1000).toISOString(),
            impressions: r.promo.impressions,
            clicks: r.promo.clicks,
          }
        : undefined,
    } satisfies Ad;
  });
}
